CREATE TABLE [dbo].[AdminUnitType] (
	[Id] INT IDENTITY (1, 1) NOT NULL,
	[Code] VARCHAR (255) NOT NULL,
	[Name] VARCHAR (255) NOT NULL,
	[Description] VARCHAR (255) NULL,
	CONSTRAINT [PK_AdminUnitType] PRIMARY KEY CLUSTERED ([Id] ASC),
	UNIQUE NONCLUSTERED ([Code] ASC)
);

