CREATE TABLE [dbo].[Country] (
	[Id] INT IDENTITY (1,1) PRIMARY KEY CLUSTERED,
	[IsoCode] CHAR (2) UNIQUE NOT NULL,
	[Name] NVARCHAR (100) NOT NULL,
	[IsActive] BIT DEFAULT 0 NOT NULL
);
GO

CREATE NONCLUSTERED INDEX [IX_Country_IsoCode] ON [dbo].[Country]([IsoCode] ASC) WITH (FILLFACTOR = 90);
GO
