//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoleSwitcher.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        public ApplicationUser()
        {
            this.UserToRoleToAdminUnits = new HashSet<UserToRoleToAdminUnit>();
        }
    
        public int Id { get; set; }
        public System.Guid ObjectGUID { get; set; }
        public string DisplayName { get; set; }
        public string Department { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string JobTitle { get; set; }
        public string Telephone { get; set; }
        public string Country { get; set; }
        public Nullable<int> DefaultCountryId { get; set; }
        public bool Enabled { get; set; }
        public Nullable<int> ApplicationCountryDepartmentId { get; set; }
        public Nullable<int> SelectedCountryId { get; set; }
        public string ExternalUserName { get; set; }
        public string ExternalUserPasswordHash { get; set; }
        public string ExternalUserSecurityStamp { get; set; }
        public string Discriminator { get; set; }
    
        public virtual ICollection<UserToRoleToAdminUnit> UserToRoleToAdminUnits { get; set; }
    }
}
