//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoleSwitcher.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestLocation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
        public int AdminUnitId { get; set; }
        public bool IsActive { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Town { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public Nullable<double> GeoLat { get; set; }
        public Nullable<double> GeoLng { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual AdminUnit AdminUnit { get; set; }
    }
}
