//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoleSwitcher.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCentre
    {
        public int Id { get; set; }
        public string CentreNumber { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public int AdminUnitId { get; set; }
        public string Address { get; set; }
        public string Administrator { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual AdminUnit AdminUnit { get; set; }
    }
}
