DECLARE  @RO AS TABLE (Type VARCHAR(255), Name VARCHAR(255))

INSERT INTO @RO VALUES ('Education', 'British Council')
INSERT INTO @RO VALUES ('Education', 'AA School')
INSERT INTO @RO VALUES ('Education', 'Aarhus University')
INSERT INTO @RO VALUES ('Education', 'Aberdeen University')
INSERT INTO @RO VALUES ('Education', 'Abu Dhabi Men''s College')
INSERT INTO @RO VALUES ('Education', 'Abu Dhabi University')
INSERT INTO @RO VALUES ('Education', 'Abu Dhabi Vocational Education Training Institution')
INSERT INTO @RO VALUES ('Education', 'ACK')
INSERT INTO @RO VALUES ('Government', 'ACT Government')
INSERT INTO @RO VALUES ('Employer', 'ADCO')
INSERT INTO @RO VALUES ('Education', 'ADVETI')
INSERT INTO @RO VALUES ('Professional Body', 'AIMS Global Education')
INSERT INTO @RO VALUES ('Education', 'AIS St Helens, NZ')
INSERT INTO @RO VALUES ('Education', 'Al Ain Colleges')
INSERT INTO @RO VALUES ('Government', 'Alberta Immigrant Nominee Program')
INSERT INTO @RO VALUES ('Education', 'Algonquin College')
INSERT INTO @RO VALUES ('Education', 'Alpha International Academy')
INSERT INTO @RO VALUES ('Education', 'American College Dublin')
INSERT INTO @RO VALUES ('Education', 'American University in Egypt')
INSERT INTO @RO VALUES ('Education', 'American University in the Emirates')
INSERT INTO @RO VALUES ('Education', 'Anglia Ruskin University')
INSERT INTO @RO VALUES ('Education', 'Applied Science Private University')
INSERT INTO @RO VALUES ('Education', 'Assumption University')
INSERT INTO @RO VALUES ('Education', 'Auckland University of Technology (AUT)')
INSERT INTO @RO VALUES ('Education', 'Auston Institute of Management, Singapore')
INSERT INTO @RO VALUES ('Government', 'Australian Embassy Belgrade')
INSERT INTO @RO VALUES ('Government', 'Australian Health Practitioner Regulation Agency (AHPRA)')
INSERT INTO @RO VALUES ('Education', 'Australian Institute for Teaching and School Leadership (AITSL)')
INSERT INTO @RO VALUES ('Education', 'Australian Institute of Business')
INSERT INTO @RO VALUES ('Professional Body', 'Australian Physiotherapy Council')
INSERT INTO @RO VALUES ('Employer', 'Aviation and Travel Training Group')
INSERT INTO @RO VALUES ('Education', 'Avondale University')
INSERT INTO @RO VALUES ('Employer', 'Backcheck')
INSERT INTO @RO VALUES ('Education', 'Ball State University')
INSERT INTO @RO VALUES ('Education', 'Bath Spa University')
INSERT INTO @RO VALUES ('Education', 'Bay of Plenty Polytechnic')
INSERT INTO @RO VALUES ('Education', 'Bellerbys College')
INSERT INTO @RO VALUES ('Education', 'Birkbeck, University of London')
INSERT INTO @RO VALUES ('Education', 'Birmingham City University')
INSERT INTO @RO VALUES ('Education', 'Blekinge Institute of Technology')
INSERT INTO @RO VALUES ('Education', 'Bond University')
INSERT INTO @RO VALUES ('Education', 'Boston Universiy, United States')
INSERT INTO @RO VALUES ('Education', 'Bournemouth University')
INSERT INTO @RO VALUES ('Education', 'British Higher School of Art and Design, Moscow')
INSERT INTO @RO VALUES ('Education', 'Brunel University, UK')
INSERT INTO @RO VALUES ('Education', 'CAH Vilentum University of Applied Sciences')
INSERT INTO @RO VALUES ('Education', 'California State University')
INSERT INTO @RO VALUES ('Education', 'Californian State University')
INSERT INTO @RO VALUES ('Education', 'Cambridge Education Group')
INSERT INTO @RO VALUES ('Employer', 'Campers Immigration')
INSERT INTO @RO VALUES ('Government', 'Canada Border Services Agency')
INSERT INTO @RO VALUES ('Education', 'Cape Breton University, Canada')
INSERT INTO @RO VALUES ('Education', 'Capilano University')
INSERT INTO @RO VALUES ('Education', 'Capitol School of Business and Management')
INSERT INTO @RO VALUES ('Education', 'Cardiff Metropolitan University')
INSERT INTO @RO VALUES ('Education', 'Carleton University')
INSERT INTO @RO VALUES ('Education', 'Carnegie Mellon University')
INSERT INTO @RO VALUES ('Education', 'Cass Business School, UK')
INSERT INTO @RO VALUES ('Education', 'Centennial College, Canada')
INSERT INTO @RO VALUES ('Education', 'Central College Nottingham')
INSERT INTO @RO VALUES ('Education', 'Central Queensland University (CQU)')
INSERT INTO @RO VALUES ('Education', 'Centre for Executive and Professional Education')
INSERT INTO @RO VALUES ('Professional Body', 'Certified Practicing Accountants (CPA) Australia')
INSERT INTO @RO VALUES ('Education', 'Chalmers University of Technology')
INSERT INTO @RO VALUES ('Education', 'Charles Darwin University')
INSERT INTO @RO VALUES ('Education', 'Charles Sturt University, Australia')
INSERT INTO @RO VALUES ('Education', 'Chiang Mai University')
INSERT INTO @RO VALUES ('Government', 'Citizenship & Immigration Canada (CIC)')
INSERT INTO @RO VALUES ('Education', 'City College Nottingham')
INSERT INTO @RO VALUES ('Education', 'City of Bath College')
INSERT INTO @RO VALUES ('Education', 'City of Bristol College, UK')
INSERT INTO @RO VALUES ('Education', 'City of Glasgow College')
INSERT INTO @RO VALUES ('Education', 'City University London')
INSERT INTO @RO VALUES ('Education', 'City University Seattle')
INSERT INTO @RO VALUES ('Education', 'College of Physicians and Surgeons of British Columbia')
INSERT INTO @RO VALUES ('Education', 'College of the North Atlantic Qatar')
INSERT INTO @RO VALUES ('Education', 'Columbia College, Vancouver, Canada')
INSERT INTO @RO VALUES ('Education', 'Computer College')
INSERT INTO @RO VALUES ('Education', 'Concordia University, Canada')
INSERT INTO @RO VALUES ('Education', 'Coquitlam College')
INSERT INTO @RO VALUES ('Education', 'Cordon Bleu Australia')
INSERT INTO @RO VALUES ('Education', 'CPA Australia')
INSERT INTO @RO VALUES ('Education', 'Cranfield University')
INSERT INTO @RO VALUES ('Employer', 'Credence')
INSERT INTO @RO VALUES ('Education', 'Crown Institute of Studies, NZ')
INSERT INTO @RO VALUES ('Education', 'Curtin College')
INSERT INTO @RO VALUES ('Education', 'Curtin University')
INSERT INTO @RO VALUES ('Education', 'Curtin University in Singapore')
INSERT INTO @RO VALUES ('Government', 'Czech Republic Embassy')
INSERT INTO @RO VALUES ('Education', 'Danube University Krems')
INSERT INTO @RO VALUES ('Government', 'Department for Manufacturing, Innovation, Trade, Resources and Energy, Immigration South Australia')
INSERT INTO @RO VALUES ('Government', 'Department of Education, Canada')
INSERT INTO @RO VALUES ('Government', 'Department of Education, Employment & Workplace Relations (DEEWR)')
INSERT INTO @RO VALUES ('Government', 'Department of Immigration and Border Protection')
INSERT INTO @RO VALUES ('Government', 'Department of Internal Affairs, NZ')
INSERT INTO @RO VALUES ('Education', 'Department of Labour and Industrial Relations')
INSERT INTO @RO VALUES ('Government', 'Department of South Australia')
INSERT INTO @RO VALUES ('Education', 'DePaul University')
INSERT INTO @RO VALUES ('Education', 'Docklands Academy London')
INSERT INTO @RO VALUES ('Education', 'Doncaster College')
INSERT INTO @RO VALUES ('Education', 'Dongguk University')
INSERT INTO @RO VALUES ('Education', 'Douglas College International (Canada)')
INSERT INTO @RO VALUES ('Education', 'Duke University')
INSERT INTO @RO VALUES ('Education', 'Durham Business School, UK')
INSERT INTO @RO VALUES ('Education', 'Durham College Canada')
INSERT INTO @RO VALUES ('Education', 'Durham University')
INSERT INTO @RO VALUES ('Government', 'Economic Development Directorate, ACT Government')
INSERT INTO @RO VALUES ('Education', 'Edghill University')
INSERT INTO @RO VALUES ('Education', 'Edinburgh Napier University')
INSERT INTO @RO VALUES ('Education', 'Edith Cowan University')
INSERT INTO @RO VALUES ('Education', 'Education and Training International, Department of Training and Workforce Development')
INSERT INTO @RO VALUES ('Education', 'EF Education First')
INSERT INTO @RO VALUES ('Government', 'Embassy of Canada')
INSERT INTO @RO VALUES ('Government', 'Embassy of Latvia (in China)')
INSERT INTO @RO VALUES ('Government', 'Embassy of the Republic of Korea in India')
INSERT INTO @RO VALUES ('Government', 'Embassy of the United Arab Emirates')
INSERT INTO @RO VALUES ('Education', 'Embry-Riddle Aeronautical University')
INSERT INTO @RO VALUES ('Professional Body', 'Engineers Australia')
INSERT INTO @RO VALUES ('Education', 'Ethames Graduate School, UK')
INSERT INTO @RO VALUES ('Education', 'EXTERNAL - NON RO')
INSERT INTO @RO VALUES ('Education', 'Falmouth University')
INSERT INTO @RO VALUES ('Education', 'Federation University Australia')
INSERT INTO @RO VALUES ('Education', 'Finnish British Society')
INSERT INTO @RO VALUES ('Employer', 'First Advantage')
INSERT INTO @RO VALUES ('Education', 'Flinders University')
INSERT INTO @RO VALUES ('Education', 'Florida Coastal School of Law')
INSERT INTO @RO VALUES ('Education', 'Florida Institute of Technology')
INSERT INTO @RO VALUES ('Government', 'Foreign Employment Division')
INSERT INTO @RO VALUES ('Education', 'Full Sail University')
INSERT INTO @RO VALUES ('Professional Body', 'General Dental Council, UK')
INSERT INTO @RO VALUES ('Professional Body', 'General Medical Council, UK')
INSERT INTO @RO VALUES ('Education', 'George Brown College, Canada')
INSERT INTO @RO VALUES ('Government', 'German Embassy in Pakistan')
INSERT INTO @RO VALUES ('Education', 'German Institute of Science and Technology in Singapore')
INSERT INTO @RO VALUES ('Education', 'German University of Technology in Oman (GUtech)')
INSERT INTO @RO VALUES ('Education', 'Glasgow Caledonian University')
INSERT INTO @RO VALUES ('Education', 'Glynd?r University London')
INSERT INTO @RO VALUES ('Government', 'Government of Saskatchewan')
INSERT INTO @RO VALUES ('Education', 'Greenwich School of Management')
INSERT INTO @RO VALUES ('Education', 'Griffith University, QL')
INSERT INTO @RO VALUES ('Education', 'Group Colleges Australia')
INSERT INTO @RO VALUES ('Education', 'GSM London')
INSERT INTO @RO VALUES ('Education', 'Guildhall College London')
INSERT INTO @RO VALUES ('Education', 'Guildhall School of Music and Drama')
INSERT INTO @RO VALUES ('Education', 'HAAGA-HELIA UAS             ')
INSERT INTO @RO VALUES ('Education', 'HCT')
INSERT INTO @RO VALUES ('Education', 'Helsinki Metropolita University of Applied Science')
INSERT INTO @RO VALUES ('Education', 'Henley College Coventry')
INSERT INTO @RO VALUES ('Education', 'Heriott Watt University')
INSERT INTO @RO VALUES ('Employer', 'Hireright')
INSERT INTO @RO VALUES ('Education', 'Hogeschool van Amsterdam')
INSERT INTO @RO VALUES ('Education', 'Hogeschool-Universiteit Brussel')
INSERT INTO @RO VALUES ('Education', 'Holland Hogeschool')
INSERT INTO @RO VALUES ('Education', 'HU University of Applied Sciences')
INSERT INTO @RO VALUES ('Education', 'Humber Institute of Technogy and Advanced Learning')
INSERT INTO @RO VALUES ('Government', 'Hungarian Embassy in China')
INSERT INTO @RO VALUES ('Education', 'IDP Education Pty Ltd')
INSERT INTO @RO VALUES ('Government', 'Immigration New Zealand')
INSERT INTO @RO VALUES ('Government', 'Immigration Services, Island Development Services Inc')
INSERT INTO @RO VALUES ('Education', 'Imperial College')
INSERT INTO @RO VALUES ('Education', 'Insearch')
INSERT INTO @RO VALUES ('Professional Body', 'Institute of Chartered Accountants Australia (ICAA)')
INSERT INTO @RO VALUES ('Professional Body', 'Institute of Public Accountants')
INSERT INTO @RO VALUES ('Education', 'Internapa')
INSERT INTO @RO VALUES ('Education', 'International Admissions and Mobility Unit')
INSERT INTO @RO VALUES ('Education', 'International College of Advanced Education')
INSERT INTO @RO VALUES ('Education', 'International House Aberdeen')
INSERT INTO @RO VALUES ('Education', 'International Islamic University of Malaysia')
INSERT INTO @RO VALUES ('Education', 'International Maritme College Oman')
INSERT INTO @RO VALUES ('Education', 'International University in Geneva (IUG)')
INSERT INTO @RO VALUES ('Education', 'INTI International University & Colleges')
INSERT INTO @RO VALUES ('Education', 'INTO international Admissions')
INSERT INTO @RO VALUES ('Education', 'INTO Norwich')
INSERT INTO @RO VALUES ('Education', 'INTO University Partnerships')
INSERT INTO @RO VALUES ('Education', 'Iran University of Science and Technology')
INSERT INTO @RO VALUES ('Education', 'Istanbul Kemerburgaz University')
INSERT INTO @RO VALUES ('Education', 'Istituto Marangoni School of Fashion')
INSERT INTO @RO VALUES ('Education', 'James Cook University')
INSERT INTO @RO VALUES ('Education', 'JAMK University of Applied Science')
INSERT INTO @RO VALUES ('Education', 'John Ruskin College, Croydon')
INSERT INTO @RO VALUES ('Education', 'Jordan University of Science and Technology')
INSERT INTO @RO VALUES ('Education', 'JSP Kimep University')
INSERT INTO @RO VALUES ('Education', 'Jumeira University')
INSERT INTO @RO VALUES ('Education', 'Kaplan International Colleges')
INSERT INTO @RO VALUES ('Education', 'Kaplan, UK')
INSERT INTO @RO VALUES ('Education', 'Karelia University of Applied Sciences')
INSERT INTO @RO VALUES ('Education', 'Karolinska Institutet')
INSERT INTO @RO VALUES ('Government', 'Kazah Academy of Sport and Tourism')
INSERT INTO @RO VALUES ('Education', 'Kazakh Medical University of Continuing Education Almaty')
INSERT INTO @RO VALUES ('Education', 'Keele University, UK')
INSERT INTO @RO VALUES ('Education', 'Kent College')
INSERT INTO @RO VALUES ('Education', 'Kent State University, US')
INSERT INTO @RO VALUES ('Education', 'Khalagh IELTS House')
INSERT INTO @RO VALUES ('Education', 'Kings College London')
INSERT INTO @RO VALUES ('Education', 'Korean Council for University College  Education')
INSERT INTO @RO VALUES ('Education', 'KTH Royal Institute of Technology')
INSERT INTO @RO VALUES ('Education', 'Kuwait Maastricht Business School')
INSERT INTO @RO VALUES ('Education', 'Kyoto University')
INSERT INTO @RO VALUES ('Government', 'Labour Market Development, Ministry of the Economy')
INSERT INTO @RO VALUES ('Education', 'Lakehead University')
INSERT INTO @RO VALUES ('Education', 'Lamar University')
INSERT INTO @RO VALUES ('Education', 'Lancaster University')
INSERT INTO @RO VALUES ('Education', 'Lasalle College of the Arts, Singapore')
INSERT INTO @RO VALUES ('Employer', 'Launching Careers')
INSERT INTO @RO VALUES ('Education', 'Laurentian University')
INSERT INTO @RO VALUES ('Education', 'Leeds Beckett University')
INSERT INTO @RO VALUES ('Education', 'Leeds Metropolitan University')
INSERT INTO @RO VALUES ('Education', 'Leeds Professional College')
INSERT INTO @RO VALUES ('Education', 'Leiden University')
INSERT INTO @RO VALUES ('Education', 'Les Roches, Marbella Spain')
INSERT INTO @RO VALUES ('Education', 'Liaoning University of Traditional Chinese')
INSERT INTO @RO VALUES ('Education', 'Lincoln University')
INSERT INTO @RO VALUES ('Education', 'LIncoln University NZ')
INSERT INTO @RO VALUES ('Education', 'Linkoping University')
INSERT INTO @RO VALUES ('Education', 'Liverpool Hope University')
INSERT INTO @RO VALUES ('Education', 'Liverpool International College')
INSERT INTO @RO VALUES ('Education', 'Liverpool John Moores University')
INSERT INTO @RO VALUES ('Education', 'Liverpool School of Tropical Medicine')
INSERT INTO @RO VALUES ('Education', 'London College of Accountancy, UK')
INSERT INTO @RO VALUES ('Education', 'London Guildhall College')
INSERT INTO @RO VALUES ('Education', 'London Metropolitan University')
INSERT INTO @RO VALUES ('Education', 'London School of Business & Finance, UK')
INSERT INTO @RO VALUES ('Education', 'London School of Business and Finance Canada')
INSERT INTO @RO VALUES ('Education', 'London School of Economics')
INSERT INTO @RO VALUES ('Education', 'Loughborough University')
INSERT INTO @RO VALUES ('Education', 'LSI Portsmouth')
INSERT INTO @RO VALUES ('Education', 'Ludwig-Maximilians-Universität')
INSERT INTO @RO VALUES ('Education', 'Lund University')
INSERT INTO @RO VALUES ('Education', 'Luther Seminary')
INSERT INTO @RO VALUES ('Employer', 'M Anderson')
INSERT INTO @RO VALUES ('Education', 'Macmaster University')
INSERT INTO @RO VALUES ('Education', 'Macquarie University')
INSERT INTO @RO VALUES ('Education', 'Management Development Institute of Singapore')
INSERT INTO @RO VALUES ('Education', 'Manchester Academy of English')
INSERT INTO @RO VALUES ('Education', 'Manchester College of Management Sciences Ltd')
INSERT INTO @RO VALUES ('Education', 'Manchester Metropolitan University')
INSERT INTO @RO VALUES ('Government', 'Manitoba Provincial Nominee Program, Department of Labour & Immigration, Canada')
INSERT INTO @RO VALUES ('Government', 'MARA')
INSERT INTO @RO VALUES ('Education', 'Massey University')
INSERT INTO @RO VALUES ('Education', 'Mayflower College')
INSERT INTO @RO VALUES ('Education', 'McMaster University')
INSERT INTO @RO VALUES ('Professional Body', 'Medical Council, Ireland')
INSERT INTO @RO VALUES ('Employer', 'Metaco Computing services Co')
INSERT INTO @RO VALUES ('Education', 'METU, Turkey')
INSERT INTO @RO VALUES ('Education', 'MFH')
INSERT INTO @RO VALUES ('Education', 'Middle Tennessee University')
INSERT INTO @RO VALUES ('Education', 'Middlesex Uninversity')
INSERT INTO @RO VALUES ('Education', 'Middlesex University, UK')
INSERT INTO @RO VALUES ('Government', 'Migration Review Tribunal')
INSERT INTO @RO VALUES ('Education', 'Milwaukee School of Engineering')
INSERT INTO @RO VALUES ('Government', 'Ministry of Business Immigration and Employment')
INSERT INTO @RO VALUES ('Government', 'Ministry of Business, Innovation & Employment, New Zealand')
INSERT INTO @RO VALUES ('Government', 'Ministry of Jobs, Tourism and Skills Training')
INSERT INTO @RO VALUES ('Education', 'Minnesota State University')
INSERT INTO @RO VALUES ('Education', 'Monash University')
INSERT INTO @RO VALUES ('Education', 'Monash University Malaysia')
INSERT INTO @RO VALUES ('Education', 'Monash University South Africa')
INSERT INTO @RO VALUES ('Employer', 'Morvarid Darya Travel Agency')
INSERT INTO @RO VALUES ('Education', 'Murdoch University')
INSERT INTO @RO VALUES ('Education', 'Mu''tah University, Jordan')
INSERT INTO @RO VALUES ('Education', 'NAIT')
INSERT INTO @RO VALUES ('Education', 'Napier University')
INSERT INTO @RO VALUES ('Education', 'National College of Ireland')
INSERT INTO @RO VALUES ('Employer', 'Net City Education')
INSERT INTO @RO VALUES ('Government', 'New Brunswick Provincial Nominee Program')
INSERT INTO @RO VALUES ('Education', 'New College of the Humanities')
INSERT INTO @RO VALUES ('Education', 'New York Institute of Technology')
INSERT INTO @RO VALUES ('Education', 'New York University')
INSERT INTO @RO VALUES ('Education', 'Newcaste International College')
INSERT INTO @RO VALUES ('Education', 'Newcastle University')
INSERT INTO @RO VALUES ('Education', 'Niagara College')
INSERT INTO @RO VALUES ('Education', 'Nilai University')
INSERT INTO @RO VALUES ('Education', 'Nippissing University')
INSERT INTO @RO VALUES ('Education', 'NMIT')
INSERT INTO @RO VALUES ('Education', 'Northbrook College, Sussex')
INSERT INTO @RO VALUES ('Education', 'Northumbria University')
INSERT INTO @RO VALUES ('Education', 'Northumbria University (Thailand Office)')
INSERT INTO @RO VALUES ('Education', 'Norwegian Business School')
INSERT INTO @RO VALUES ('Education', 'Nottingham Trent University')
INSERT INTO @RO VALUES ('Education', 'Nottingham University')
INSERT INTO @RO VALUES ('Education', 'Novia University of Applied Sciences')
INSERT INTO @RO VALUES ('Education', 'Nuffic')
INSERT INTO @RO VALUES ('Professional Body', 'Nursing and Midwifery Accreditation Council')
INSERT INTO @RO VALUES ('Professional Body', 'Nursing and Midwifery Board, Australia')
INSERT INTO @RO VALUES ('Professional Body', 'Nursing and Midwifery Board, Ireland')
INSERT INTO @RO VALUES ('Professional Body', 'Nursing and Midwifery Council, UK')
INSERT INTO @RO VALUES ('Professional Body', 'Nursing Council of New Zealand')
INSERT INTO @RO VALUES ('Professional Body', 'NZ Psychologists Board')
INSERT INTO @RO VALUES ('Government', 'Office of Immigration, Population and Settlement, Canada')
INSERT INTO @RO VALUES ('Education', 'Okanagan College')
INSERT INTO @RO VALUES ('Education', 'Oklahoma State University Institute of Technology')
INSERT INTO @RO VALUES ('Education', 'Ontario College of Teachers')
INSERT INTO @RO VALUES ('Education', 'Oregon State University')
INSERT INTO @RO VALUES ('Education', 'Oxford Business College')
INSERT INTO @RO VALUES ('Education', 'Pepperdine University')
INSERT INTO @RO VALUES ('Education', 'Perth Institute of Business and Technology (PIBT)')
INSERT INTO @RO VALUES ('Professional Body', 'Pharmacy Council of New Zealand')
INSERT INTO @RO VALUES ('Professional Body', 'Physiologist Board of New Zealand')
INSERT INTO @RO VALUES ('Education', 'PolyU, Hong Kong')
INSERT INTO @RO VALUES ('Employer', 'Professional Nursing Services Ltd')
INSERT INTO @RO VALUES ('Government', 'Province of Manitoba')
INSERT INTO @RO VALUES ('Education', 'PSB Academy')
INSERT INTO @RO VALUES ('Education', 'Purdue Universtiy Calumet')
INSERT INTO @RO VALUES ('Education', 'Queen Margaret University')
INSERT INTO @RO VALUES ('Education', 'Queen Margaret University Edinburgh')
INSERT INTO @RO VALUES ('Education', 'Queen Mary University of London')
INSERT INTO @RO VALUES ('Education', 'Queens  University Belfast')
INSERT INTO @RO VALUES ('Education', 'Queensland Institute of Business and Technology at Griffith University')
INSERT INTO @RO VALUES ('Education', 'Queensland University of Technology')
INSERT INTO @RO VALUES ('Education', 'Rhein Waal University of Applied Science')
INSERT INTO @RO VALUES ('Education', 'Riyadh College of Technology ')
INSERT INTO @RO VALUES ('Education', 'RMIT University')
INSERT INTO @RO VALUES ('Education', 'Robert Gordon University')
INSERT INTO @RO VALUES ('Education', 'Rotterdam Business School')
INSERT INTO @RO VALUES ('Education', 'Royal Academy of Music')
INSERT INTO @RO VALUES ('Professional Body', 'Royal College of Physicians')
INSERT INTO @RO VALUES ('Education', 'Royal Holloway, University of London')
INSERT INTO @RO VALUES ('Education', 'Royal Roads University')
INSERT INTO @RO VALUES ('Education', 'RTU Riga Business School')
INSERT INTO @RO VALUES ('Education', 'Ruhr University Bochum')
INSERT INTO @RO VALUES ('Education', 'Russo English')
INSERT INTO @RO VALUES ('Education', 'Ryerson University')
INSERT INTO @RO VALUES ('Education', 'Said Business School')
INSERT INTO @RO VALUES ('Education', 'Saint Mary''s University (Canada)')
INSERT INTO @RO VALUES ('Education', 'San Francisco State University')
INSERT INTO @RO VALUES ('Education', 'Saskatchewan Institute of Applied Science and Technology (SIAST)')
INSERT INTO @RO VALUES ('Education', 'SATAC')
INSERT INTO @RO VALUES ('Education', 'Saudi Arabian Cultural Bureau')
INSERT INTO @RO VALUES ('Education', 'Saudi Electronic University')
INSERT INTO @RO VALUES ('Education', 'SEGi Institute')
INSERT INTO @RO VALUES ('Education', 'SEGI University')
INSERT INTO @RO VALUES ('Education', 'Seneca College of Applied Arts & Technology')
INSERT INTO @RO VALUES ('Education', 'Sheffield Hallam')
INSERT INTO @RO VALUES ('Education', 'Sheridan College')
INSERT INTO @RO VALUES ('Education', 'Simon Fraser University')
INSERT INTO @RO VALUES ('Education', 'Singapore Institute of Management')
INSERT INTO @RO VALUES ('Education', 'Sino British College')
INSERT INTO @RO VALUES ('Education', 'SOAS')
INSERT INTO @RO VALUES ('Education', 'South Australian Institute for Business and Technology')
INSERT INTO @RO VALUES ('Education', 'South Australian Tertiary Admissions Centre (SATAC)')
INSERT INTO @RO VALUES ('Education', 'South Dakota School of Mines and Technology')
INSERT INTO @RO VALUES ('Education', 'South London College')
INSERT INTO @RO VALUES ('Education', 'South Quay College, UK')
INSERT INTO @RO VALUES ('Education', 'South Thames College')
INSERT INTO @RO VALUES ('Education', 'Southern Illinois University')
INSERT INTO @RO VALUES ('Education', 'Stenden University of applied sciences')
INSERT INTO @RO VALUES ('Education', 'Strathclyde University')
INSERT INTO @RO VALUES ('Employer', 'Study Co')
INSERT INTO @RO VALUES ('Education', 'Study Group')
INSERT INTO @RO VALUES ('Education', 'Sunderland Foundation Campus')
INSERT INTO @RO VALUES ('Education', 'Swansea University')
INSERT INTO @RO VALUES ('Education', 'Swinburne University of Technology')
INSERT INTO @RO VALUES ('Education', 'Sydney Institute of Business and Technology')
INSERT INTO @RO VALUES ('Education', 'TAFESA')
INSERT INTO @RO VALUES ('Education', 'TAMUC')
INSERT INTO @RO VALUES ('Education', 'Taylors College')
INSERT INTO @RO VALUES ('Education', 'Taylors University Malaysia')
INSERT INTO @RO VALUES ('Professional Body', 'Teacher Registration Board')
INSERT INTO @RO VALUES ('Education', 'Teeside University')
INSERT INTO @RO VALUES ('Education', 'The Australian National University')
INSERT INTO @RO VALUES ('Education', 'The College of Saint Rose')
INSERT INTO @RO VALUES ('Education', 'The Hague University of Applied Sciences')
INSERT INTO @RO VALUES ('Education', 'The Hong Kong Polytechnic University')
INSERT INTO @RO VALUES ('Education', 'The Language Gallery')
INSERT INTO @RO VALUES ('Education', 'The Manchester College')
INSERT INTO @RO VALUES ('Professional Body', 'The Opticians Board')
INSERT INTO @RO VALUES ('Education', 'The Petroleum Institute')
INSERT INTO @RO VALUES ('Education', 'The Professional Bar and Restaurant School, NZ')
INSERT INTO @RO VALUES ('Education', 'The University of Adelaide')
INSERT INTO @RO VALUES ('Education', 'The University of Auckland')
INSERT INTO @RO VALUES ('Education', 'The University of Buckingham')
INSERT INTO @RO VALUES ('Education', 'The University of Manchester')
INSERT INTO @RO VALUES ('Education', 'The University of New South Wales')
INSERT INTO @RO VALUES ('Education', 'The University of Tennessee')
INSERT INTO @RO VALUES ('Education', 'The University of Texas at San Antonio')
INSERT INTO @RO VALUES ('Education', 'Tilburg Law School')
INSERT INTO @RO VALUES ('Education', 'Tilburg University')
INSERT INTO @RO VALUES ('Government', 'TKDK - Turkey')
INSERT INTO @RO VALUES ('Government', 'Trades Recognition Australia (TRA)')
INSERT INTO @RO VALUES ('Education', 'UCAS')
INSERT INTO @RO VALUES ('Education', 'UCLA Anderson School of Management')
INSERT INTO @RO VALUES ('Education', 'UCSI Professional Academy')
INSERT INTO @RO VALUES ('Government', 'UK Visas and Immigration')
INSERT INTO @RO VALUES ('Education', 'UKEC International')
INSERT INTO @RO VALUES ('Education', 'UMFLINT')
INSERT INTO @RO VALUES ('Education', 'Uni-assist Germany')
INSERT INTO @RO VALUES ('Education', 'Unitec, Institute of Technology')
INSERT INTO @RO VALUES ('Education', 'Universidad Externado, Bogota')
INSERT INTO @RO VALUES ('Education', 'Universitat Pompeu Fabra')
INSERT INTO @RO VALUES ('Education', 'Universiti Kebangsaan Malaysia')
INSERT INTO @RO VALUES ('Education', 'Universiti Teknologi Malaysia')
INSERT INTO @RO VALUES ('Education', 'Universiti Teknologi PETRONAS')
INSERT INTO @RO VALUES ('Education', 'Universiti Tenaga Nasional')
INSERT INTO @RO VALUES ('Education', 'Universitii Malaysia Sarawak')
INSERT INTO @RO VALUES ('Education', 'University Admissions Finland')
INSERT INTO @RO VALUES ('Education', 'University Canada West')
INSERT INTO @RO VALUES ('Education', 'University College Birmingham')
INSERT INTO @RO VALUES ('Education', 'University College London (UCL)')
INSERT INTO @RO VALUES ('Education', 'University College Santa Barbara (USA)')
INSERT INTO @RO VALUES ('Education', 'University Foundation Programme')
INSERT INTO @RO VALUES ('Education', 'University of Aberdeen, UK')
INSERT INTO @RO VALUES ('Education', 'University of Aberwystwyth')
INSERT INTO @RO VALUES ('Education', 'University of Alberta')
INSERT INTO @RO VALUES ('Education', 'University of Applied Sciences')
INSERT INTO @RO VALUES ('Education', 'University of Aston')
INSERT INTO @RO VALUES ('Education', 'University of Bangor')
INSERT INTO @RO VALUES ('Education', 'University of Bath')
INSERT INTO @RO VALUES ('Education', 'University of Bedfordshire')
INSERT INTO @RO VALUES ('Education', 'University of Birmingham')
INSERT INTO @RO VALUES ('Education', 'University of Bournemouth')
INSERT INTO @RO VALUES ('Education', 'University of Bradford, UK')
INSERT INTO @RO VALUES ('Education', 'University of Bristol, UK')
INSERT INTO @RO VALUES ('Education', 'University of British Columbia')
INSERT INTO @RO VALUES ('Education', 'University of Brunel')
INSERT INTO @RO VALUES ('Education', 'University of Cambridge')
INSERT INTO @RO VALUES ('Education', 'University of Cambridge (ICE)')
INSERT INTO @RO VALUES ('Education', 'University of Canberra')
INSERT INTO @RO VALUES ('Education', 'University of Canterbury, NZ')
INSERT INTO @RO VALUES ('Education', 'University of Cardiff')
INSERT INTO @RO VALUES ('Education', 'University of Chester (UK)')
INSERT INTO @RO VALUES ('Education', 'University of Chicago')
INSERT INTO @RO VALUES ('Education', 'University of Colorado Denver')
INSERT INTO @RO VALUES ('Education', 'University of Coventry')
INSERT INTO @RO VALUES ('Education', 'University of Dallas')
INSERT INTO @RO VALUES ('Education', 'University of Dhaka')
INSERT INTO @RO VALUES ('Education', 'University of Dubai')
INSERT INTO @RO VALUES ('Education', 'University of Durham')
INSERT INTO @RO VALUES ('Education', 'University of East Anglia')
INSERT INTO @RO VALUES ('Education', 'University of Edinburgh')
INSERT INTO @RO VALUES ('Education', 'University of Edinburgh Business School')
INSERT INTO @RO VALUES ('Education', 'University of Essex')
INSERT INTO @RO VALUES ('Education', 'University of Exeter, UK')
INSERT INTO @RO VALUES ('Education', 'University of Glasgow')
INSERT INTO @RO VALUES ('Education', 'University of Groningen')
INSERT INTO @RO VALUES ('Education', 'University of Hertfordshire')
INSERT INTO @RO VALUES ('Education', 'University of Huddersfield')
INSERT INTO @RO VALUES ('Education', 'University of IDAHO (in Moscow)')
INSERT INTO @RO VALUES ('Education', 'University of Johannesburg')
INSERT INTO @RO VALUES ('Education', 'University of Kent, UK')
INSERT INTO @RO VALUES ('Education', 'University of Lancaster')
INSERT INTO @RO VALUES ('Education', 'University of Leeds')
INSERT INTO @RO VALUES ('Education', 'University of Leicester, UK')
INSERT INTO @RO VALUES ('Education', 'University of Lincoln')
INSERT INTO @RO VALUES ('Education', 'University of Liverpool')
INSERT INTO @RO VALUES ('Education', 'University of London, UK')
INSERT INTO @RO VALUES ('Education', 'University of Loughborough')
INSERT INTO @RO VALUES ('Education', 'University of Malaya')
INSERT INTO @RO VALUES ('Education', 'University of Manchester Business School')
INSERT INTO @RO VALUES ('Education', 'University of Melbourne')
INSERT INTO @RO VALUES ('Education', 'University of Miami, US')
INSERT INTO @RO VALUES ('Education', 'University of Michigan')
INSERT INTO @RO VALUES ('Education', 'University of New England')
INSERT INTO @RO VALUES ('Education', 'University of New England, Australia')
INSERT INTO @RO VALUES ('Education', 'University of New South Wales (UNSW)')
INSERT INTO @RO VALUES ('Education', 'University of Newcastle')
INSERT INTO @RO VALUES ('Education', 'University of Newcastle, Australia')
INSERT INTO @RO VALUES ('Education', 'University of Northumbria')
INSERT INTO @RO VALUES ('Education', 'University of Norway')
INSERT INTO @RO VALUES ('Education', 'University of Nottingham')
INSERT INTO @RO VALUES ('Education', 'University of Oslo')
INSERT INTO @RO VALUES ('Education', 'University of Otago')
INSERT INTO @RO VALUES ('Education', 'University of Ottawa')
INSERT INTO @RO VALUES ('Education', 'University of Oxford')
INSERT INTO @RO VALUES ('Education', 'University of Plymouth')
INSERT INTO @RO VALUES ('Education', 'University of Portsmouth')
INSERT INTO @RO VALUES ('Education', 'University of Queensland')
INSERT INTO @RO VALUES ('Education', 'University of Reading')
INSERT INTO @RO VALUES ('Education', 'University of Salford')
INSERT INTO @RO VALUES ('Education', 'University of Saskatchewan')
INSERT INTO @RO VALUES ('Education', 'University of Science and Technology, Korea')
INSERT INTO @RO VALUES ('Education', 'University of Sheffield')
INSERT INTO @RO VALUES ('Education', 'University of South Australia')
INSERT INTO @RO VALUES ('Education', 'University of Southampton, UK')
INSERT INTO @RO VALUES ('Education', 'University of Southern Denmark')
INSERT INTO @RO VALUES ('Education', 'University of Southern Queensland')
INSERT INTO @RO VALUES ('Education', 'University of St Andrews')
INSERT INTO @RO VALUES ('Education', 'University of Stavanger')
INSERT INTO @RO VALUES ('Education', 'University of Stirling')
INSERT INTO @RO VALUES ('Education', 'University of Strathclyde')
INSERT INTO @RO VALUES ('Education', 'University of Surrey')
INSERT INTO @RO VALUES ('Education', 'University of Sussex')
INSERT INTO @RO VALUES ('Education', 'University of Swansea')
INSERT INTO @RO VALUES ('Education', 'University of Sydney')
INSERT INTO @RO VALUES ('Education', 'University of Tasmania')
INSERT INTO @RO VALUES ('Education', 'University of Technology Sydney (UTS)')
INSERT INTO @RO VALUES ('Education', 'University of Texas in San Antonio')
INSERT INTO @RO VALUES ('Education', 'University of the Highlands and Islands')
INSERT INTO @RO VALUES ('Education', 'University of the Incarnate Word')
INSERT INTO @RO VALUES ('Education', 'University of the West of Scotland')
INSERT INTO @RO VALUES ('Education', 'University of Toronto, Canada')
INSERT INTO @RO VALUES ('Education', 'University of Twente, Netherlands')
INSERT INTO @RO VALUES ('Education', 'University of Ulster')
INSERT INTO @RO VALUES ('Education', 'University of Ulster London and Birmingham Branch Campuses')
INSERT INTO @RO VALUES ('Education', 'University of Utrecht')
INSERT INTO @RO VALUES ('Education', 'University of Waikato')
INSERT INTO @RO VALUES ('Education', 'University of Wales Trinity St David')
INSERT INTO @RO VALUES ('Education', 'University of Warwick')
INSERT INTO @RO VALUES ('Education', 'University of Washington')
INSERT INTO @RO VALUES ('Education', 'University of Waterloo')
INSERT INTO @RO VALUES ('Education', 'University of West of London')
INSERT INTO @RO VALUES ('Education', 'University of Western Australia')
INSERT INTO @RO VALUES ('Education', 'University of Western Sydney')
INSERT INTO @RO VALUES ('Education', 'University of Westminster')
INSERT INTO @RO VALUES ('Education', 'University of Windsor, Canada')
INSERT INTO @RO VALUES ('Education', 'University of Witwatersrand')
INSERT INTO @RO VALUES ('Education', 'University of Wollongong')
INSERT INTO @RO VALUES ('Education', 'University of Wolverhampton')
INSERT INTO @RO VALUES ('Education', 'University Putra Malaysia')
INSERT INTO @RO VALUES ('Education', 'Universty of Northampton')
INSERT INTO @RO VALUES ('Education', 'UNP')
INSERT INTO @RO VALUES ('Education', 'UNSW')
INSERT INTO @RO VALUES ('Education', 'UNSW Global')
INSERT INTO @RO VALUES ('Education', 'Utah State University')
INSERT INTO @RO VALUES ('Education', 'UTAS')
INSERT INTO @RO VALUES ('Education', 'Utrecht University')
INSERT INTO @RO VALUES ('Education', 'UTS:INSEARCH')
INSERT INTO @RO VALUES ('Education', 'Vancouver Island University, Canada')
INSERT INTO @RO VALUES ('Employer', 'VFS Global')
INSERT INTO @RO VALUES ('Education', 'Victoria University of Wellington')
INSERT INTO @RO VALUES ('Education', 'Vietnam National University, Hanoi')
INSERT INTO @RO VALUES ('Education', 'Vision College')
INSERT INTO @RO VALUES ('Education', 'Vista Business College')
INSERT INTO @RO VALUES ('Education', 'Wageningen University')
INSERT INTO @RO VALUES ('Education', 'Wangeningen University')
INSERT INTO @RO VALUES ('Education', 'Wichita State University')
INSERT INTO @RO VALUES ('Education', 'Wilkes University')
INSERT INTO @RO VALUES ('Education', 'Wittenborg University')
INSERT INTO @RO VALUES ('Education', 'Yale University')
INSERT INTO @RO VALUES ('Education', 'Zayed University')
INSERT INTO @RO VALUES ('Education', 'ZHGU')


MERGE dbo.Organisation AS Target
	USING 
	(
		SELECT RO.Name, 1, OrganisationType.Id, NULL FROM @RO RO
		JOIN OrganisationType 
			ON OrganisationType.Name = RO.Type
	) AS Source ( Name, IsActive,organisationTypeId,Code)

	ON (Target.Name = Source.Name)

	WHEN MATCHED THEN 
		UPDATE SET Name = Source.Name , IsActive = Source.IsActive

	-- insert new rows 
	WHEN NOT MATCHED BY TARGET THEN 
		INSERT (Name,IsActive,OrganisationTypeId,Code) 
		VALUES (Name,IsActive,OrganisationTypeId,Code) 

	-- delete rows that are in the target but not the source 
	WHEN NOT MATCHED BY SOURCE THEN 
			UPDATE SET IsActive = 0;
	

-- Set code for British Council as BC
IF EXISTS (SELECT NULL FROM dbo.Organisation WHERE Name = 'British Council' AND Code IS NULL) BEGIN
	UPDATE dbo.Organisation
		SET Code = 'BC'
	WHERE Name = 'British Council'
END

-- Create codes
WHILE (SELECT COUNT(*) FROM dbo.Organisation WHERE Code IS NULL) > 0 BEGIN

	DECLARE @OrgId INT, @NewCode VARCHAR(255)
	SELECT TOP 1 @OrgId = Id, @NewCode = Name
		FROM dbo.Organisation WHERE Code IS NULL
	
	SET @NewCode = REPLACE(@NewCode, 'THE ','')
	SET @NewCode = REPLACE(@NewCode, 'Polytechnic','POLY')
	SET @NewCode = REPLACE(@NewCode, 'University of','UNI')
	SET @NewCode = REPLACE(@NewCode, 'University','UNI')
	SET @NewCode = REPLACE(@NewCode, 'Universiti','UNI')
	SET @NewCode = REPLACE(@NewCode, 'Universidad','UNI')
	SET @NewCode = REPLACE(@NewCode, 'Universität','UNI')
	SET @NewCode = REPLACE(@NewCode, 'College','COL')
	SET @NewCode = REPLACE(@NewCode, 'School','SCH')
	SET @NewCode = LTRIM(RTRIM(@NewCode))
	SET @NewCode = REPLACE(@NewCode, ':', '')
	SET @NewCode = REPLACE(@NewCode, ',', '')
	SET @NewCode = REPLACE(@NewCode, '(', '')
	SET @NewCode = REPLACE(@NewCode, ')','')
	SET @NewCode = REPLACE(@NewCode, '-',' ')
	SET @NewCode = REPLACE(@NewCode, '&','')
	SET @NewCode = REPLACE(@NewCode, '''','')
	SET @NewCode = REPLACE(@NewCode, '   ', ' ')
	SET @NewCode = REPLACE(@NewCode, '  ', ' ')
	SET @NewCode = REPLACE(@NewCode, ' ', '_')
	SET @NewCode = LEFT(UPPER(@NewCode), 150)
	
	UPDATE dbo.Organisation
		SET Code = @NewCode
		WHERE Id = @OrgId
	
END