DECLARE @schemakeys TABLE (
	[Role] VARCHAR(25) NOT NULL,
	[IncidentClass] VARCHAR(7) NOT NULL,
	[SchemaKey] VARCHAR (50) NOT NULL,
	[MapIncludesChildren] BIT NOT NULL,
	PRIMARY KEY ([Role], [IncidentClass])
);

-- standard schema mappings to role and incident class
INSERT INTO @schemakeys VALUES ('GLOBAL_OPERATIONS','ROOT','INCIDENT_SCHEMA_STANDARD',0);
INSERT INTO @schemakeys VALUES ('GLOBAL_OPERATIONS','CCOM','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('GLOBAL_OPERATIONS','CSTA','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('GLOBAL_OPERATIONS','OTHR','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('GLOBAL_OPERATIONS','RPRO','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('GLOBAL_OPERATIONS','SYSE','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('GLOBAL_OPERATIONS','TDCA','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('GLOBAL_OPERATIONS','TMAT','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('GLOBAL_OPERATIONS','TLOC','INCIDENT_SCHEMA_STANDARD',1);

INSERT INTO @schemakeys VALUES ('RMT','ROOT','INCIDENT_SCHEMA_STANDARD',0);
INSERT INTO @schemakeys VALUES ('RMT','CCOM','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('RMT','CSTA','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('RMT','OTHR','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('RMT','RPRO','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('RMT','SYSE','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('RMT','TDCA','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('RMT','TMAT','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('RMT','TLOC','INCIDENT_SCHEMA_STANDARD',1);

INSERT INTO @schemakeys VALUES ('VT','ROOT','INCIDENT_SCHEMA_STANDARD',0);

INSERT INTO @schemakeys VALUES ('CCT','ROOT','INCIDENT_SCHEMA_STANDARD',0);
INSERT INTO @schemakeys VALUES ('CCT','CCOM','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('CCT','CSTA','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('CCT','OTHR','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('CCT','RPRO','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('CCT','SYSE','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('CCT','TDCA','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('CCT','TMAT','INCIDENT_SCHEMA_STANDARD',1);
INSERT INTO @schemakeys VALUES ('CCT','TLOC','INCIDENT_SCHEMA_STANDARD',1);

-- Standard (with sub category) schema mappings to role and incident class
-- (none currently)

-- Investigation schema mappings to role and incident class
INSERT INTO @schemakeys VALUES ('GLOBAL_OPERATIONS','INET','INCIDENT_SCHEMA_INVESTIGATION',0);
INSERT INTO @schemakeys VALUES ('RMT','INET','INCIDENT_SCHEMA_INVESTIGATION',0);
INSERT INTO @schemakeys VALUES ('VT','INET','INCIDENT_SCHEMA_INVESTIGATION',0);
INSERT INTO @schemakeys VALUES ('CCT','INET','INCIDENT_SCHEMA_INVESTIGATION',0);
INSERT INTO @schemakeys VALUES ('GLOBAL_OPERATIONS','PRRC','INCIDENT_SCHEMA_INVESTIGATION',1);
INSERT INTO @schemakeys VALUES ('RMT','PRRC','INCIDENT_SCHEMA_INVESTIGATION',1);
INSERT INTO @schemakeys VALUES ('VT','PRRC','INCIDENT_SCHEMA_INVESTIGATION',1);

-- Verifications schema mappings to role and incident class
INSERT INTO @schemakeys VALUES ('GLOBAL_OPERATIONS','VERIFI1','INCIDENT_SCHEMA_VERIFICATION', 1);
INSERT INTO @schemakeys VALUES ('RMT','VERIFI1','INCIDENT_SCHEMA_VERIFICATION', 1);
INSERT INTO @schemakeys VALUES ('VT','VERIFI1','INCIDENT_SCHEMA_VERIFICATION', 1);
INSERT INTO @schemakeys VALUES ('CCT','VERIFI1','INCIDENT_SCHEMA_VERIFICATION', 1);

-- test centre schema mappings to test center staff role and incident class
INSERT INTO @schemakeys VALUES ('TCS','ROOT','INCIDENT_SCHEMA_TEST_CENTRE',0);
INSERT INTO @schemakeys VALUES ('TCS','CCOM','INCIDENT_SCHEMA_TEST_CENTRE',1);
INSERT INTO @schemakeys VALUES ('TCS','CSTA','INCIDENT_SCHEMA_TEST_CENTRE',1);
INSERT INTO @schemakeys VALUES ('TCS','RPRO','INCIDENT_SCHEMA_TEST_CENTRE',1);
INSERT INTO @schemakeys VALUES ('TCS','SYSE','INCIDENT_SCHEMA_TEST_CENTRE',1);
INSERT INTO @schemakeys VALUES ('TCS','TDCA','INCIDENT_SCHEMA_TEST_CENTRE',1);
INSERT INTO @schemakeys VALUES ('TCS','TMAT','INCIDENT_SCHEMA_TEST_CENTRE',1);
INSERT INTO @schemakeys VALUES ('TCS','TLOC','INCIDENT_SCHEMA_TEST_CENTRE',1);
INSERT INTO @schemakeys VALUES ('TCS','OTHR','INCIDENT_SCHEMA_TEST_CENTRE',1);

-- view only
INSERT INTO @schemakeys VALUES ('CCT','PRRC','INCIDENT_SCHEMA_STANDARD_VIEWONLY',1);
INSERT INTO @schemakeys VALUES ('TCS','INET','INCIDENT_SCHEMA_TEST_CENTRE_VIEWONLY',1);


MERGE INTO dbo.SchemaKeyMap AS Target
	USING (
		SELECT ar.Id, cls.Id, keys.SchemaKey, MapIncludesChildren
		FROM @schemakeys keys
		LEFT JOIN dbo.ApplicationRole ar
			ON ar.Code = keys.Role
		LEFT JOIN dbo.IncidentClass cls
			ON cls.Code = keys.IncidentClass
	) AS Source ([ApplicationRoleId], [IncidentClassId], SchemaKey,[MapIncludesChildren])
	ON (Target.ApplicationRoleId = Source.ApplicationRoleId AND Target.IncidentClassId = Source.IncidentClassId)

	WHEN MATCHED THEN
		UPDATE SET SchemaKey = Source.SchemaKey, [MapIncludesChildren] = Source.[MapIncludesChildren]

	WHEN NOT MATCHED THEN 
		INSERT ([ApplicationRoleId], [IncidentClassId], SchemaKey, [MapIncludesChildren])
		VALUES (Source.[ApplicationRoleId], Source.[IncidentClassId], SchemaKey, [MapIncludesChildren])

	WHEN NOT MATCHED BY SOURCE THEN 
		DELETE;