MERGE INTO [stage].[TestCentre] AS Target
	USING (
	VALUES 
		('996','ASPECT ILA', 'ASPECT ILA', 'UNITED KINGDOM','UKIA','Kaplan International College Bournemouth, 130 - 136 Poole Road, Westbourne, Bournemouth BH4 9EF','Nicola Waine','nicola.waine@kaplan.com',' ielts@uea.ac.uk'),
		('4555','INTO UNIVERSITY OF EAST ANGLIA', 'INTO UNIVERSITY OF EAST ANGLIA', 'UNITED KINGDOM','UKIA','Norwich Research Park, Norwich, Norfolk, NR4 7TJ','Olena Skorokhod','O.Skorokhod@uea.ac.uk',NULL),
		('9654','SOUTH EASTERN REGIONAL COLLEGE', 'SOUTH EASTERN REGIONAL COLLEGE', 'UNITED KINGDOM','UKIA','Examinations Department - IELTS, South Eastern Regional College, Castle Park Road, Bangor BT20 4TD','Zia Nazar','ielts@serc.ac.uk',NULL),
		('10126','EALING, HAMMERSMITH CAMPUS', 'EALING, HAMMERSMITH CAMPUS', 'UNITED KINGDOM','UKIA','Gliddon Road, Hammersmith, London W14 9BL','Agata Podlewska','agatap@gspace.wlc.ac.uk',NULL),
		('10294','INTERNATIONAL HOUSE LONDON', 'INTERNATIONAL HOUSE LONDON', 'UNITED KINGDOM','UKIA','16 Stukeley Street, Covent Garden, London WC2B 5LQ','Eve Truszkowska','Eve.Truszkowska@ihlondon.com','ielts2@eurocentres.com'),
		('10629','LONDON EUROCENTRES ELTHAM', 'LONDON EUROCENTRES ELTHAM', 'UNITED KINGDOM','UKIA','70 Court Road, Eltham, London SE9 5NP','Laura O''Brien','ieltsadmin@eurocentres.com',NULL),
		('10747','BELLERBYS COLLEGE', 'BELLERBYS COLLEGE', 'UNITED KINGDOM','UKIA','Bounty House, Stowage, Greenwich, London SE8 3DE','Lisa Evripidou','LEvripidou@studygroup.com','enas@southwark.ac.uk'),
		('10850','SOUTHWARK  COLLEGE', 'SOUTHWARK  COLLEGE', 'UNITED KINGDOM','UKIA','LeSoCo, BB19, Lewisham Way, London SE4 1UT','Janet Lunam','janet.lunam@lesoco.ac.uk',NULL),
		('14537','THE LONDON EXAM CENTRE', 'THE LONDON EXAM CENTRE', 'UNITED KINGDOM','UKIA','Wimbledon School of English, 41 Worple Road, Wimbledon, London SW19 4JZ','Sandro Saviolo','sandro@wimbledon-school.ac.uk',NULL),
		('16430','COLCHESTER ENGLISH STUDY CENTR', 'COLCHESTER ENGLISH STUDY CENTR', 'UNITED KINGDOM','UKIA','19 Lexden Road, Colchester, Essex CO3 3PW','Max Walsh','ielts@cesc.co.uk',NULL),
		('22107','ANGLIA RUSKIN UNIVERSITY, CAMB', 'ANGLIA RUSKIN UNIVERSITY, CAMB', 'UNITED KINGDOM','UKIA','East Road, Cambridge CB1 1PT','Mandy Holland','ielts@anglia.ac.uk',NULL),
		('25256','LEICESTER  COLLEGE', 'LEICESTER  COLLEGE', 'UNITED KINGDOM','UKIA','Abbey Park Campus, Room APA 1.08, Painter St. Leicester LE1 3WA','Harpal Thiara','hthiara@lec.ac.uk',NULL),
		('31135','WARWICKSHIRE COLLEGE', 'WARWICKSHIRE COLLEGE', 'UNITED KINGDOM','UKIA','Rugby Campus, Technology Drive, Rugby, Warwickshire, CV21 1AR','Tina Rees','IELTS@warkscol.ac.uk','jc@fs1.elt.umist.ac.uk'),
		('32342','UNIVERSITY LANGUAGE CENTRE M/C', 'UNIVERSITY LANGUAGE CENTRE M/C', 'UNITED KINGDOM','UKIA','University Language Centre, Oddfellows Hall, 97 Grosvenor Street, Manchester, M1 7HF','Sandra Aksenaviciute','ielts@manchester.ac.uk',NULL),
		('34400','ENGLISH LANGUAGE UNIT, LIVERPO', 'ENGLISH LANGUAGE UNIT, LIVERPO', 'UNITED KINGDOM','UKIA','School of English Liverpool University Chatham Street, Liverpool L69 7ZR','Neelum Gajree','N.Gajree@liverpool.ac.uk','ielts@shu.ac.uk'),
		('36698','TESOL CENTRE, SHEFFIELD', 'TESOL CENTRE, SHEFFIELD', 'UNITED KINGDOM','UKIA','Faculty of Development and Society TESOL Centre, , Sheffield Hallam University, Howard St, City Campus, Sheffield S1 1WB','Seyi Junaid','ielts@shu.ac.uk',NULL),
		('39520','SUNDERLAND COLLEGE', 'SUNDERLAND COLLEGE', 'UNITED KINGDOM','UKIA','The Bede Centre, Durham Road, Sunderland SR3 4AH','Joan Callaghan / Andrea Murray','ieltstest@sunderlandcollege.ac.uk',NULL),
		('48227','HARROGATE  LANGUAGE ACADEMY LT', 'HARROGATE  LANGUAGE ACADEMY LT', 'UNITED KINGDOM','UKIA','8A Royal Parade, Harrogate, N Yorkshire, HG1 2SZ','Paul Elwen,','ielts@hla.co.uk',NULL),
		('48374','MELTON COLLEGE YORK', 'MELTON COLLEGE YORK', 'UNITED KINGDOM','UKIA','137 Holgate Road, York YO24 4DH','Katie Davis','office@melton-college.co.uk',' ielts-officers@bath.ac.uk'),
		('50724','ENGLISH LANGUAGE CENTRE BATH', 'ENGLISH LANGUAGE CENTRE BATH', 'UNITED KINGDOM','UKIA','English Language Centre, Academic Skills Centre, The Avenue, Claverton Down, Bath,  BA2 7AY','Shelley Bromley/Petra Pekova','ielts@bath.ac.uk',NULL),
		('55142','RICHARD LANGUAGE COLLEGE  BOUR', 'RICHARD LANGUAGE COLLEGE  BOUR', 'UNITED KINGDOM','UKIA','Richard Language College, 43-45 Wimborne Road, Bournemouth, BH3 7AB','Mr Eg Aberson','ielts@rlc.co.uk',NULL),
		('56355','SUSSEX DOWNS COLLEGE, EASTBOUR', 'SUSSEX DOWNS COLLEGE, EASTBOUR', 'UNITED KINGDOM','UKIA','Room 134, Grove House, Cross-levels Way, Eastbourne, East Sussex, BN21 2UF','Kathryn Newman','Kathryn.Newman@sussexdowns.ac.uk',NULL),
		('58534','LANGUAGE SPECIALISTS INTERNATI', 'LANGUAGE SPECIALISTS INTERNATI', 'UNITED KINGDOM','UKIA','1-13 Lord Montgomery Way, Portsmouth PO1 2AH','Angel MA','IELTS@lsi-Portsmouth.co.uk','C.Madeley@ukc.ac.uk'),
		('61402','CHAUCER COLLEGE CANTERBURY', 'CHAUCER COLLEGE CANTERBURY', 'UNITED KINGDOM','UKIA','University Road, Canterbury, Kent CT2 7LJ','Chris Madeley','c.madeley@chaucercollege.co.uk',NULL),
		('62352','KINGS SCHOOL OXFORD', 'KINGS SCHOOL OXFORD', 'UNITED KINGDOM','UKIA','21 ST MICHAEL''S STREET, ST MICHAEL''S CAMPUS, KING''S OXFORD, OXFORD, OX1 2EB OX1 2EB','Sally Fenn','ielts@oxford.kingscolleges.com',NULL),
		('64441','THE LANGUAGE CENTRE UNIVERSITY', 'THE LANGUAGE CENTRE UNIVERSITY', 'UNITED KINGDOM','UKIA','School of English and Languages, University Library and Learning Centre, Room 15LC03 (LRC), Faculty of Arts & Human Sciences, University of Surrey, Guildford Surrey GU2 7XH','James Gre','ielts@surrey.ac.uk',NULL),
		('65596','HOVE  EMBASSY BRIGHTON', 'HOVE  EMBASSY BRIGHTON', 'UNITED KINGDOM','UKIA','Brighton Study Centre, 1 Billinton Way, Brighton BN1 4LF','Alex Whisken','awhisken@studygroup.com',NULL),
		('68406','BANGOR UNIVERSITY', 'BANGOR UNIVERSITY', 'UNITED KINGDOM','UKIA','c/o MAIN ARTS POST ROOM, BANGOR UNIVERSITY, COLLEGE ROAD, BANGOR, GWYNEDD LL57 2DG','Nick Parker','ielts@bangor.ac.uk',NULL),
		('69744','EDINBURGH  BASIL PATERSON COLL', 'EDINBURGH  BASIL PATERSON COLL', 'UNITED KINGDOM','UKIA','66 Queen Street, Edinburgh EH2 4NA','Claire Samuel','claire.samuel@basilpaterson.co.uk','o.getty@qub.ac.uk'),
		('71202','THE LANGUAGE CENTRE BELFAST', 'THE LANGUAGE CENTRE BELFAST', 'UNITED KINGDOM','UKIA','Queen''s University Belfast, The McClay Library, 10 College Park, Belfast BT7 1LP','Brenda Davis','B.Davis@qub.ac.uk',NULL),
		('73000','INTERNATIONAL STUDY AND LANGUA', 'INTERNATIONAL STUDY AND LANGUA', 'UNITED KINGDOM','UKIA','University Of Reading, Po Box 218, Reading RG6 6AA','Bethany Tribe','b.v.tribe@reading.ac.uk',NULL),
		('73450','THE ENGLISH LANGUAGE TEACHING', 'THE ENGLISH LANGUAGE TEACHING', 'UNITED KINGDOM','UKIA','The University Of Sheffield, 78 Hoyle Street, Sheffield S3 7LG','Matthew Watson','eltc.ielts@sheffield.ac.uk',NULL),
		('74555','BURTON AND SOUTH DERBYSHIRE CO', 'BURTON AND SOUTH DERBYSHIRE CO', 'UNITED KINGDOM','UKIA','Lichfield Street, Burton Upon Trent, Staffordshire DE14 3RL','Anna Burke','anna.burke@bsdc.ac.uk','zts@aber.ac.uk'),
		('82963','UNIVERSITY OF WALES ABERYSTWYT', 'UNIVERSITY OF WALES ABERYSTWYT', 'UNITED KINGDOM','UKIA','International English Centre, Aberystwyth University, Llandinam Building, Penglais, Aberystwyth, Wales SY23 3DB','Helen Hayes','ielts@aber.ac.uk',NULL),
		('84212','THE MAYFLOWER COLLEGE,  PLYMOU', 'THE MAYFLOWER COLLEGE,  PLYMOU', 'UNITED KINGDOM','UKIA','The Mayflower College, 1 Radford Road, The Hoe, Plymouth PL1 3BY','Suzie Emery','suzie@maycoll.co.uk',NULL),
		('90056','GLASGOW CALEDONIAN UNIVERSITY', 'GLASGOW CALEDONIAN UNIVERSITY', 'UNITED KINGDOM','UKIA','70 Cowcaddens Road, Glasgow G4 0BA','Shirley Meighan','Shirley.Meighan@gcu.ac.uk',NULL),
		('AE001','BRITISH COUNCIL', 'DUBAI', 'UNITED ARAB EMIRATES','AMESA1','Tariq Bin Ziyad Street, Near Rashid Hospital, P.O. Box 1636, Dubai, UAE','Hasan Mahmud','Hasan.Mahmud@britishcouncil.org',NULL),
		('AE110','BRITISH COUNCIL', 'ABU DHABI', 'UNITED ARAB EMIRATES','AMESA1','Khalidiya Area, Al Nasr Street, PO Box 46523, Abu Dhabi, United Arab Emirates','Shakil Ahmad','Shakil.Ahmad@ae.britishcouncil.org',NULL),
		('AE113','CERT CENTRE FOR TRAINING AND A', 'CERT CENTRE FOR TRAINING AND A', 'UNITED ARAB EMIRATES','AMESA1','Higher Colleges of Technology, Dubai Men''s College, Sheikh Mohamed Bin Zayed Road, Exit 44, Academic City, PO Box 15825, Dubai, United Arab Emirates','Arhit Abraham','arhit.abraham@hct.ac.ae',NULL),
		('AE119','ZAYED UNIVERSITY', 'ZAYED UNIVERSITY', 'UNITED ARAB EMIRATES','AMESA1','Dubai Campus, Po Box 19282, Academic City, Al Ruwayyah, Dubai, United Arab Emirates','Ann Stephenson','ann.stephenson@zu.ac.ae',NULL),
		('AE222','ABU DHABI UNIVERSITY', 'ABU DHABI UNIVERSITY', 'UNITED ARAB EMIRATES','AMESA1','Institute For Enterprise Development (Ied), P.O. Box 59911, Abu Dhabi, United Arab Emirates','Souheil Nassour','souheil.nassour@adu.ac.ae',NULL),
		('AE501','BRITISH COUNCIL', 'UAE UNIVERSITY', 'UNITED ARAB EMIRATES','AMESA1','Continuing Education Centre, ELT Unit - IELTS Centre, P.O. Box 15551, Al Ain, United Arab Emirates','Dr. Saif Khalifa Al-Shaali','IELTS.administrator@uaeu.ac.ae',NULL),
		('AF009','BRITISH COUNCIL', 'AFGHANISTAN', 'AFGHANISTAN','AMESA2','British Embassy Compound, 15th Street Round About, Wazir Akbar Khan, Kabul, Afghanistan','Mohammad Anwar','Mohammad.Anwar@britishcouncil.org',NULL),
		('AL001','BRITISH COUNCIL', 'ALBANIA', 'ALBANIA','Europe','British Council, C/O British Embassy, Rr Skenderbej, Nr 12, Tirana, Albania','Ismete Kroi','Ismete.Kroi@britishcouncil.org',NULL),
		('AM001','BRITISH COUNCIL', 'ARMENIA', 'ARMENIA','Europe','British Council, British Embassy, 9 Alex Manoogian, Yerevan 0070, Armenia','Liana Sakapetoyan','liana.sakapetoyan@britishcouncil.am','efortin@acci.org.ar'),
		('AR609','BUENOS AIRES - AACI', 'BUENOS AIRES - AACI', 'ARGENTINA','UKIA','Suipacha 1333, 1011 Buenos Aires, Argentina, CUIT (Tax ID): 30-52550539-8','Flavia Hayes','fhayes@aaci.org.ar','exams@britishcouncil.at;'),
		('AT040','BRITISH COUNCIL', 'VIENNA', 'AUSTRIA','Europe','Exams Services, Siebensterngasse 21, A-1070 Vienna, Austria','Nina Maier','nina.maier@britishcouncil.at','Paul.Hilder@britishcouncil.az'),
		('AZ001','BRITISH COUNCIL', 'BAKU', 'AZERBAIJAN','Europe','8th Floor, The Landmark III Building, 96 Nizami Street, Baku AZ1010, Azerbaijan','Nargiz Zaidova','nargiz.zaidova@britishcouncil.az',NULL),
		('BA001','BRITISH COUNCIL', 'BOSNIA & HERZE', 'BOSNIA & HERZEGOVINA','Europe','Ljubljanska 9, 2nd Floor, 71000 Sarajevo, Bosnia and Herzegovina','Alma Vatres','alma.vatres@britishcouncil.ba','martha.gibson@bd.britishcouncil.org'),
		('BD001','BRITISH COUNCIL', 'DHAKA', 'BANGLADESH','AMESA2','British Council Dhaka, Fuller Road, Dhaka 1000, Bangladesh','Ishrat Jahan','ishrat.jahan@britishcouncil.org',NULL),
		('BD400','BRITISH COUNCIL', 'CHITTAGONG', 'BANGLADESH','AMESA2','Rafique Tower, 8th Floor, 92 Agrabad C/A, Chittagong, Bangladesh','Fahmida Khanam','Fahmida.Khanam@bd.britishcouncil.org','Pascale.laurent@britishcouncil.be'),
		('BE003','BRITISH COUNCIL', 'BRUSSELS', 'BELGIUM','Europe','Leopold Plaza, Troonstraat, Rue du Trone 108, B-1050 Brussels, Belgium','Bikash Adhikari','bikash.adhikari@britishcouncil.be','Kostadin.gavrilo@britishcouncil.bg'),
		('BG001','BRITISH COUNCIL', 'SOFIA', 'BULGARIA','Europe','No 7 Krakra Street, 1504 Sofia, Bulgaria','Dafina Ikonomova','Dafina.Ikonomova@britishcouncil.bg','examinations.services@britishcouncil.org.bh'),
		('BH001','BRITISH COUNCIL', 'BAHRAIN', 'BAHRAIN','AMESA1','P.O. Box 452, 146 Shaikh Salman Highway, Manama 356, Bahrain','Atif Kamal','Atif.Kamal@britishcouncil.org.bh','pgnoorainipgahmad@gmail.com'),
		('BN091','CFBT EDUCATION SERVICES', 'CFBT EDUCATION SERVICES', 'BRUNEI DARUSSALAM','SEA','Unit 8,  1st Floor, Block C, Kiarong Complex, Lebuhraya Sultan Haji Hassanal Bolkiah, Gadong BE1318, Brunei Darussalam','Dk Nooraini Pg Ahmad','nahmad@cfbt.org',NULL),
		('BR051','BRITISH COUNCIL', 'SAO PAULO', 'BRAZIL','UKIA','Rua Ferreira Araujo, 741 - 3, Pinheiros, 05428-002, Sao Paulo- SP, BRAZIL','Mariana Panessa','mariana.panessa@britishcouncil.org',NULL),
		('BU001','BRITISH COUNCIL', 'YANGON', 'MYANMAR','SEA','HM Ambassador, (for Cultural Attache), 78 Kannar Road, Yangon (PO Box 638), Myanmar (Burma)','Robert Tin Myint','roberttin.myint@mm.britishcouncil.org',NULL),
		('BY002','STUDY CENTRE INTERNATIONAL HOU', 'STUDY CENTRE INTERNATIONAL HOU', 'BELARUS','Europe','Masherova Avenue 10/12 - 311, Minsk, , 220005, Belarus','Valeriya Toulenkova','valeriya@ih.by','Amichaud@conestogac.on.ca'),
		('CA021','CONESTOGA COLLEGE OF  A A AND', 'CONESTOGA COLLEGE OF  A A AND', 'CANADA','UKIA','299 Doon Valley Drive, Kitchener, Ontario N2G 4M4, Canada','Christine Wach','cwach@conestogac.on.ca','jeremy.hunter@englishcanada.org'),
		('CA030','ENGLISH CANADA WORLD ORGANIZAT', 'ENGLISH CANADA WORLD ORGANIZAT', 'CANADA','UKIA','English Canada World Organization, 1190 Barrington Street, Halifax Nova Scotia, Canada B3H 2R4','Michelle Ford','michelle.ford@englishcanada.org','mojgan.habibi@ilsc.com'),
		('CA039','ILSC TORONTO', 'ILSC TORONTO', 'CANADA','UKIA','112 Elizabeth Street, 3rd floor, Office 204, Toronto, Ontario M5G 1P5','Katrin Faridani','katrin.faridani@ilsc.com',NULL),
		('CA072','BOW VALLEY COLLEGE', 'BOW VALLEY COLLEGE', 'CANADA','UKIA','345 - 6th Avenue Se, Calgary, AB, T2G 4V1, Canada','Kassian Asheshov','kasheshov@bowvalleycollege.ca',NULL),
		('CA073','ASSESSMENT CENTRE - GEORGE BRO', 'ASSESSMENT CENTRE - GEORGE BRO', 'CANADA','UKIA','341 King Street, E., Room 419, Toronto ON, M5A 1L1','Chris Hall','christopher.hall@georgebrown.ca',NULL),
		('CA075','ENGLISH LANGUAGE CENTRE', 'ENGLISH LANGUAGE CENTRE', 'CANADA','UKIA','520 University Centre, University of Manitoba, Winnipeg, MB, R3T 2N2, Canada','Joan Birrell-Bertrand','joan.birrell-bertrand@umanitoba.ca',NULL),
		('CA088','ILSC MONTREAL', 'ILSC MONTREAL', 'CANADA','UKIA','410 St Nicholas, Suite 300, Montreal, H2Y 2P5, Canada','Omid Momtahen Fakhrani','Omid.m-fakhrani@ilsc.com',NULL),
		('CA148','KAPLAN VANCOUVER', 'KAPLAN VANCOUVER', 'CANADA','UKIA','300 - 755 Burrard Street, Vancouver, V6Z 1X6, Canada','Lee Campbell','lee.campbell@kaplan.com',NULL),
		('CA250','ILSC VANCOUVER', 'ILSC VANCOUVER', 'CANADA','UKIA','555 Richards Street, Vancouver, V6B 2Z5','Sonia Fantauzzi','Sonia.fantauzzi@ilsc.com',NULL),
		('CA256','VANCOUVER MAPLE LEAF COLLEGE', 'VANCOUVER MAPLE LEAF COLLEGE', 'CANADA','UKIA','Suite 250, 815 West Hastings Street, Vancouver BC, Canada V6C 1B4','Cheryl Bodie','cbodie@languagecanada.com',NULL),
		('CA333','CANADA COLLEGE', 'CANADA COLLEGE', 'CANADA','UKIA','1118 Sainte-Catherine West #403, Montreal, Quebec, H3B 1H5','Melissa Moretto','melissa@collegecanada.com',NULL),
		('CA335','ENGLISH TESTING CANADA LTD. ET', 'ENGLISH TESTING CANADA LTD. ET', 'CANADA','UKIA','455 Spadina Ave, Unit 402, Toronto ON M5S 2G8, Canada','Laura Mannell','lmannell@myetc.ca',NULL),
		('CA336','INTERNATIONAL LANGUAGE TRAININ', 'INTERNATIONAL LANGUAGE TRAININ', 'CANADA','UKIA','Unit 1D, 1111 Franklin Blvd, Cambridge, Ontario, N1R 8B5, Canada','Lata Thomas','lthomas@iltts.ca',NULL),
		('CA338','ASSINIBOINE COMMUNITY COLLEGE', 'ASSINIBOINE COMMUNITY COLLEGE', 'CANADA','UKIA','1430 Victoria Avenue, East Brandon, MB, R7A 2A9','Sandra Mulvihill','mulvihills@assiniboine.net',NULL),
		('CH066','BRITISH COUNCIL', 'BERNE', 'SWITZERLAND','Europe','Exams Administration, Hildanusstrasse 3, 3013 Bern, Switzerland','Sarah Fabel','ielts@britishcouncil.ch',NULL),
		('CL055','INSTITUTO CHILENO BRITANICO DE', 'INSTITUTO CHILENO BRITANICO DE', 'CHILE','UKIA','Instituto Chileno Britanico De Cultura, Santa Lucia 124, Santiago, Chile','Rahmi Nazarala Grez','rnazarala@britanico.cl',NULL),
		('CLS01','INSTITUTO CHILENO BRITANICO DE', 'INSTITUTO CHILENO BRITANICO DE', 'CHILE','UKIA','Instituto Chileno Britanico De Cultura, Santa Lucia 124, Santiago Centro 8320222, Chile','Rahmi Nazarala','Rahmi.nazarala@britishcouncil.cl',NULL),
		('CM001','BRITISH COUNCIL', 'CAMEROON', 'CAMEROON','AMESA1','British Council, BP 818 Yaounde,C/o British High Commission,Avenue Winston Churchill, Cameroon','Caroline Ndifor','Caroline.Ndifor@britishcouncil.cm','Liliana.Biglou@gh.britishcouncil.org'),
		('CN001','BRITISH COUNCIL', 'BEIJING', 'CHINA','SEA','British Council, 7/Floor Landmark Tower 1, 8 East Third Ring Road North, Chaoyang District, Beijing, 100004, China, Peoples Republic','Tracy Xu','xu.shuo@britishcouncil.org.cn','Joanna.mok@britishcouncil.org.cn'),
		('CN002','BRITISH COUNCIL', 'GUANGZHOU', 'CHINA','SEA','BC Education Consulting (Beijing)Co. Ltd Guangzhou Branch, Room 06-07 30/F, Teem Tower 208 Tianhe Road, Guangzhou 510620, Peoples Republic of China','Linda Li','Linda.Li@britishcouncil.org.cn','Mona.chen@britishcouncil.org.cn'),
		('CN004','BRITISH COUNCIL', 'SHANGHAI', 'CHINA','SEA','Room 01-03/08 16/F Garden Square, 968 West Beijing Road, Shanghai 200041, China','Jackie Hu','jackie.hu@britishcouncil.org.cn',NULL),
		('CN172','BRITISH COUNCIL', 'CHONGQING', 'CHINA','SEA','BC Education Consulting (Beijing)Co. Ltd Chongqing Branch, Room 5-7, 28F Metropolitan Tower, No. 68 Zourong Rd, Yuzhong District, 400010 Chongqing, China','Phyllis Luo','Phyllis.Luo@britishcouncil.org.cn',NULL),
		('CO001','BRITISH COUNCIL', 'BOGOTA', 'COLOMBIA','UKIA','Examinations and Marketing Officer, Carrera 9, No. 76-49, 5th Floor, Bogota, Colombia, South America','Ana Maria Martinez','anamaria.martinez@britishcouncil.org','britsch@racsa.co.cr'),
		('CR001','BRITED S.A.', 'BRITED S.A.', 'COSTA RICA','UKIA','Colegio Británico de Costa Rica, Del final de Boulevard de Rohmoser, 125 Metros Norte, Urbanización Santa Catalina, Pavas, San José, Costa Rica','Ivette Cedeno','icedeno@bscr.ed.cr',NULL),
		('CU003','BRITISH COUNCIL', 'CUBA', 'CUBA','UKIA','The British Embassy, Calle 34# 702, 7m Avenue, Miramar, C. Habana 11300, CUBA','Sandra Del Pino','Sandra.delPino@britishcouncil.org',NULL),
		('CY006','BRITISH COUNCIL', 'CYPRUS', 'CYPRUS','Europe','1-3 Aristotelous Street, 1011 Nicosia, PO Box 25654, 1387 Nicosia, Cyprus','Constantina Pambis','exams.enquiries@cy.britishcouncil.org','info.praha@britishcouncil.cz'),
		('CZ001','BRITISH COUNCIL', 'PRAGUE', 'CZECH REPUBLIC','Europe','British Council, Examinations Services, Bredovsky dvur, Politickych veznu 13, 110 00 Prague 1, Czech Republic','Pavla Stara','pavla.stara@britishcouncil.cz','caroline.murdoch@britishcouncil.de'),
		('DE708','BRITISH COUNCIL', 'OUNCIL', 'GERMANY','Europe','Alexanderplatz 1, 10178 Berlin, Germany','Andreas Kulawik','andreas.kulawik@britishcouncil.de',NULL),
		('DK035','EDU DANMARK APS', 'EDU DANMARK APS', 'DENMARK','Europe','Nikolaj Plads 26, 2nd. floor, DK-1067 Copenhagen K, Denmark','Cisca de Wilde','ielts@edu-danmark.dk',NULL),
		('DZ003','LANGUAGE SOLUTIONS ALGERIA', 'LANGUAGE SOLUTIONS ALGERIA', 'ALGERIA','AMESA1','Villa N°5 - Route de Dely Ibrahim, (Rue distante en face de l''Hôtel El Amir), Cheraga, 16002, Algeria','IELTS Administrator','dzexams@lsalgerie.com',NULL),
		('DZ015','LANGUAGE SOLUTIONS ALGERIA SAR', 'LANGUAGE SOLUTIONS ALGERIA SAR', 'ALGERIA','AMESA1','Villa N°5 - Route de Dely Ibrahim, (Rue distante en face de l''Hôtel El Amir), Cheraga, 16002, Algeria','IELTS Administrator','dzexams@lsalgerie.com','bcyu@britishcouncil.org.yu'),
		('EA001','BRITISH COUNCIL', 'SERBIA', 'SERBIA & MONTENEGRO','Europe','Terazije 8/1, PO Box 248, 11000 Belgrade, Serbia','Marko Zlataric','marko.zlataric@britishcouncil.rs',NULL),
		('EE003','TALLINN UNIVERSITY LANGUAGE CE', 'TALLINN UNIVERSITY LANGUAGE CE', 'ESTONIA','Europe','Narva Mnt. 29, 10120 Tallinn, Estonia','Sirle Kivihall','sirle.kivihall@tlu.ee',NULL),
		('EG001','BRITISH COUNCIL', 'CAIRO', 'EGYPT','AMESA1','The British Embassy, Kasr El Dobara, Garden City, Cairo, Egypt','Muhammad Mansour','Muhammad.Mansour@britishcouncil.org.eg',NULL),
		('EG002','BRITISH COUNCIL', 'ALEXANDRIA', 'EGYPT','AMESA1','11 Mahmoud Abou El Ela Street, Kafr Abdou, Roushdy, Alexandria, Egypt','Injy Elnimr','Injy.Elnimr@britishcouncil.org.eg',NULL),
		('ES017','BRITISH COUNCIL', 'BARCELONA', 'SPAIN','Europe','The British Institute, Calle Amigo 83, 08021 Barcelona, Spain','Aicha Camara','Aixa.Camara@britishcouncil.es','begona.pradera@britishcouncil.es'),
		('ES024','BRITISH COUNCIL', 'MADRID', 'SPAIN','Europe','The British Council, Po General Martinez Campos 3, 28010 Madrid, Spain','Emilia Biesek','emilia.biesek@britishcouncil.es','Irune.Iriondo@britishcouncil.es'),
		('ES032','BRITISH COUNCIL', 'BILBAO', 'SPAIN','Europe','Instituto Britanico, Avda. Lehendakari Aguirre 29-2, 48014 Deusto-Bilbao, Vizcaya, Spain','Natalia Garduno','exams.bilbao@britishcouncil.es',' Nebyu.yohannes@et.britishcouncil.org'),
		('ET001','BRITISH COUNCIL', 'ADDIS ABABA', 'ETHIOPIA','AMESA2','Exam Department, British Council, Comoros Street, P.O Box 1043, Addis Ababa, Ethiopia','Asrer Terefe','aster.terefe@et.britishcouncil.org',NULL),
		('FI001','FINNISH-BRITISH SOCIETY', 'FINNISH-BRITISH SOCIETY', 'FINLAND','Europe','Finish-British Society, Fredrikinkatu 20 A 9, 00120 Helsinki, Finland','Raimo Ahonen','raimo.ahonen@finnbrit.fi',NULL),
		('FR585','BRITISH COUNCIL', 'PARIS', 'FRANCE','Europe','The British Council (IELTS), 9 Rue de Constantine, 75007 Paris Cedex 07, FRANCE','Hugo Hadjipetrou','chandi.burlton@britishcouncil.fr',NULL),
		('GB008','SOUTHAMPTON UNIVERSITY', 'SOUTHAMPTON UNIVERSITY', 'UNITED KINGDOM','UKIA','Faculty of Humanities, Student Office, Building 65, Avenue Campus, Southampton SO17 1BJ','Peter Cresswell','ielts@soton.ac.uk',NULL),
		('GB501','SCHOOL OF LANGUAGES, ASTON UNI', 'SCHOOL OF LANGUAGES, ASTON UNI', 'UNITED KINGDOM','UKIA','Aston University, Aston Triangle, Birmingham B4 7ET','Alicia Zborowska','a.zborowska@aston.ac.uk',NULL),
		('GB507','UNIVERSITY OF WESTMINSTER', 'UNIVERSITY OF WESTMINSTER', 'UNITED KINGDOM','UKIA','32-38 Wells Street, London, W1T 3UW','Luisa Guerra','l.guerra@westminster.ac.uk','norma.hazzledine@nottingham.ac.uk'),
		('GB509','UNIVERSITY OF NOTTINGHAM', 'UNIVERSITY OF NOTTINGHAM', 'UNITED KINGDOM','UKIA','The University of Nottingham, International Office, International House - C Floor, Jubilee Campus, Wollaton Road, Nottingham, NG8 1BB','Teresa Kay','teresa.kay@nottingham.ac.uk','PeggCA@cardiff.ac.uk'),
		('GB512','CARDIFF UNIVERSITY', 'CARDIFF UNIVERSITY', 'UNITED KINGDOM','UKIA','IELTS Office, Cardiff University, Deri House, 2 -4 Park Grove, Cardiff, CF10 3BN','Karen Hanson','ieltsadmin@cardiff.ac.uk',NULL),
		('GBS01','BRITISH COUNCIL', 'BASIL PATERSON COLLEGE - EDINB', 'UNITED KINGDOM','UKIA','66 Queen Street, Edinburgh, EH2 4NA','Claire Samuel','claire.samuel@basilpaterson.co.uk',NULL),
		('GBS02','BRITISH COUNCIL', 'EALING, HAMMERSMITH AND WEST L', 'UNITED KINGDOM','UKIA','Barons Court Station, Hammersmith campus, Gliddon Road, Barons Court, London W14 9BL','Mr Alex Hallawell','alexh@gspace.wlc.ac.uk',NULL),
		('GBS03','BRITISH COUNCIL', 'ANGLIA RUSKIN UNIVERSITY', 'UNITED KINGDOM','UKIA','East Road, Cambridge, CB1 1PT','Mandy Holland','Mandy.holland@anglia.ac.uk',NULL),
		('GBS04','BRITISH COUNCIL', 'EALING HAMMERSMITH & WEST LOND', 'UNITED KINGDOM','UKIA','Hammersmith Campus, Gliddon Rd, Barons Court, London W14 9BL','Alex Hallawell','alexh@gspace.wlc.ac.uk',NULL),
		('GBS05','BRITISH COUNCIL', 'IH LONDON', 'UNITED KINGDOM','UKIA','16 Stukeley St, Covent Garden, London WC2B 5LQ','Eve Truszkowska','eve.truszkowska@ihlondon.com',NULL),
		('GBS06','BRITISH COUNCIL', 'IH LONDON', 'UNITED KINGDOM','UKIA','Greenwich School Of Management, 891 Greenford Rd, London UB6 0HE','Michal Mazanek','michal.mazanek@mobiletesting.uk.com',NULL),
		('GBS07','BRITISH COUNCIL', 'IH LONDON', 'UNITED KINGDOM','UKIA','Greenwich School of Management, 891 Greenford Rd, London, United Kingdom UB6 0HE','Michal Mazanek','michal.mazanek@mobiletesting.uk.com',NULL),
		('GBS08','BRITISH COUNCIL', 'IH LONDON', 'UNITED KINGDOM','UKIA','Greenwich School of Management, 891 Greenford Rd, London, United Kingdom UB6 0HE','Michal Mazanek','michal.mazanek@mobiletesting.uk.com',NULL),
		('GBS09','BRITISH COUNCIL', 'IH LONDON', 'UNITED KINGDOM','UKIA','Greenwich School of Management, 891 Greenford Rd, London, United Kingdom UB6 0HE','Michal Mazanek','michal.mazanek@mobiletesting.uk.com',NULL),
		('GBS10','BRITISH COUNCIL', 'IH LONDON', 'UNITED KINGDOM','UKIA','Greenwich School of Management, 891 Greenford Rd, London, United Kingdom UB6 0HE','Michal Mazanek','michal.mazanek@mobiletesting.uk.com',NULL),
		('GBS11','BRITISH COUNCIL', 'CENTRE OF ENGLISH STUDIES', 'UNITED KINGDOM','UKIA','31 Dame Street, Dublin 2','Paul Corbett','paul.corbett@britishcouncil.org','Ana.Tikaradze@britishcouncil.org.ge'),
		('GE001','BRITISH COUNCIL', 'TBILISI', 'GEORGIA','Europe','34 Rustaveli Avenue, 0108 Tblisi, Georgia','Rusudan Bakhtadze','rusudan.bakhtadze@ge.britishcouncil.org','ernestina.odame@britishcounil.org.gh'),
		('GH001','BRITISH COUNCIL', 'ACCRA', 'GHANA','AMESA1','Liberia Road, PO Box GP 771, Accra, Ghana, West Africa','Elvis Yaw Adom','elvis.yawadom@gh.britishcouncil.org',NULL),
		('GR005','BRITISH COUNCIL', 'GREECE', 'GREECE','Europe','17 Kolonaki Square, 10673, Athens, Greece','Penny Karadima','penny.karadima@britishcouncil.gr',NULL),
		('GR026','BRITISH COUNCIL', 'GREECE', 'GREECE','Europe','IELTS Administrator, 43 Tsimiski Street, 546 23 Thessaloniki, Greece','Christina Athanasiou','christina.athanasiou@britishcouncil.gr',NULL),
		('HK001','BRITISH COUNCIL', 'HONG KONG', 'HONG KONG','SEA','Examination Services, 3 Supreme Court Road, Admiralty, Hong Kong','Ms Monita Au-Yeung','examinations@britishcouncil.org.hk',NULL),
		('HR002','BRITISH COUNCIL', 'ZAGREB', 'CROATIA','Europe','British Council, Exams Admin, Palmoticeva 60/I, Zagreb, 10 000, Croatia','Ms Sanja Dragojevic','sanja.dragojevic@britishcouncil.hr',NULL),
		('HU001','BRITISH COUNCIL', 'BUDAPEST', 'HUNGARY','Europe','British Council, Madach ut 13-14 Building B.4. floor, 1075 Budapest, Hungary','Maria Bozso','maria.bozso@britishcouncil.hu',NULL),
		('ID195','BRITISH COUNCIL', 'INDONESIA', 'INDONESIA','SEA','Indonesia Stock Exchange Tower II, 16th Floor, JL. JEND. SUDIRMAN Kav. 52-53, Jakarta 12190, INDONESIA','Jane Maulani','jane.maulani@britishcouncil.or.id',NULL),
		('IE012','UNIVERSITY COLLEGE DUBLIN', 'UNIVERSITY COLLEGE DUBLIN', 'REPUBLIC OF IRELAND','UKIA','UCD Applied Language Centre, Daedalus Building, Belfield, Dublin 4, , Republic of Ireland','Johanna Flannery','ielts@ucd.ie',NULL),
		('IE069','CENTRE OF ENGLISH STUDIES', 'CENTRE OF ENGLISH STUDIES', 'UNITED KINGDOM','UKIA','31 Dame Street, Dublin 2, Ireland','Paul Corbett','ielts@ces-schools.com.',NULL),
		('IE899','CORK ENGLISH COLLEGE', 'CORK ENGLISH COLLEGE', 'REPUBLIC OF IRELAND','UKIA','Saint Patrick''s Bridge, Cork City, Ireland','Lidia Biskup','lidia@corkenglishcollege.ie',NULL),
		('IL001','BRITISH COUNCIL', 'TEL AVIV', 'ISRAEL','Europe','15th Floor Sason Hogi Tower, 12 Abba Hillel Road, Ramat Gan, Israel','Moran Hochberg ','moran.hochberg@britishcouncil.org',' Jagan.Kumar@in.britishcouncil.org'),
		('IN001','BRITISH COUNCIL', 'CHENNAI', 'INDIA','AMESA2','British Deputy High Commission, 737 Anna Salai, Chennai 600 002, India','Vijayalakshmi Thiyagarajan','t.vijayalakshmi@in.britishcouncil.org',NULL),
		('IN002','BRITISH COUNCIL', 'KOLKATA', 'INDIA','AMESA2','British Council Division, British High Commission, 17, Kasturba Gandhi Marg, Delhi, Pin-110001, India','Anuj Gangola','anuj.gangola@britishcouncil.org',NULL),
		('IN100','BRITISH COUNCIL', 'MUMBAI', 'INDIA','AMESA2','British Council Division, British Deputy High Commission, 901, 9th Floor, Tower 1, One Indiabulls Centre, 841 Senapati Bapat Marg, Elphinstone Road (West), Mumbai - 400 013 India','Rajesh Bhojan','Rajesh.Bhojani@in.britishcouncil.org',NULL),
		('IN120','BRITISH COUNCIL', 'NEW DELHI BRITISH HIGH COMMISS', 'INDIA','AMESA2','British Council Divison, British High Commission, 17 Kasturba Gandhi Marg, New Delhi 110 001, India','Anuj Gangola','anuj.gangola@in.britishcouncil.org',NULL),
		('IQ016','BRITISH COUNCIL', 'IRAQ', 'IRAQ','AMESA1','Engineering Faculty Campus, , Salahaddin University, , Kirkuk Road, 44002, Erbil, Iraq','Anwaar Smoar Ali','anwaar.al-somarli@britishcouncil.org',NULL),
		('IT010','BRITISH COUNCIL', 'MILAN', 'ITALY','Europe','Via Manzoni 38, 20121 Milano, ITALY','Davide Secci','ielts.milan@britishcouncil.it','ielts.naples@BritishCouncil.it'),
		('IT012','BRITISH COUNCIL', 'NAPLES', 'ITALY','Europe','Via R. Morghen 31, 80129 Naples, Italy','Vincenzo De Constanzo','vincenzo.decostanzo@britishcouncil.it',NULL),
		('IT264','BRITISH COUNCIL', 'ROME', 'ITALY','Europe','Via di San Sebasstianello 16, 00187 Rome, Italy','Chiara Messore','admin.romaesami@britishcouncil.it',NULL),
		('JM250','DEPT.LANGUAGE,LINGUISTICS AND', 'DEPT.LANGUAGE,LINGUISTICS AND', 'JAMAICA','UKIA','University Of The West Indies, Mona, Kingston 7, Jamaica','Yaneke White','ielts@uwimona.edu.jm',NULL),
		('JMS01','UNIVERSITY OF THE WEST INDIES', 'UNIVERSITY OF THE WEST INDIES', 'JAMAICA','UKIA','IELTS, c/o Department of Language Linguistics and Philosophy, Mona, Kingston 7, Jamaica','Angella O''Meally','Angella.omeally@britishcouncil.org.jm',NULL),
		('JO001','BRITISH COUNCIL', 'JORDAN', 'JORDAN','AMESA1','Examination Office/ ESOL, PO Box 634, Amman 11118, Jordan','Angie Khalil','Angie.Khalil@britishcouncil.org.jo','exams@britishcouncil.or.jp'),
		('JP090','BRITISH COUNCIL', 'JAPAN - TOKYO', 'JAPAN','SEA','1-2, Kagurazaka, Shinjuku-ku, Tokyo, 162-0825, Japan','Ms Chie Yasuda','Chie.Yasuda@britishcouncil.or.jp','exams@britishcouncil.or.jp'),
		('JP099','BRITISH COUNCIL', 'JAPAN - OSAKA', 'JAPAN','SEA','1-2, Kagurazaka, Shinjuku-ku, Tokyo, 162-0825, Japan','Ms Chie Yasuda','Chie.Yasuda@britishcouncil.or.jp','eriko_kurosawa@hotmail.com'),
		('JP500','EIKEN FOUNDATION OF JAPAN', 'EIKEN FOUNDATION OF JAPAN', 'JAPAN','SEA','55 Yokodera-machi, Shinjuku-Ku, Tokyo 162-8055, Japan','Ms Eriko Kurosawa','e-kurosawa@eiken.or.jp',NULL),
		('JP512','EIKEN FOUNDATION OF JAPAN', 'EIKEN FOUNDATION OF JAPAN', 'JAPAN','SEA','Kyotomi Bldg.7f, 1-3-16 Sonezakishinchi Kita-ku, Osaka 530-0002, Japan','Ms. Yoshie Takeuchi','y-takeuchi@eiken.or.jp','Lilian.Guantai@britishcouncil.or.ke'),
		('KE001','BRITISH COUNCIL', 'NAIROBI', 'KENYA','AMESA1','Exams Department, Upper Hill Road, Upper Hill, 00100 Nairobi, Kenya','Mandy Chana','Mandy.Chana@britishcouncil.or.ke','ielts@britishcouncil.or.kr'),
		('KR001','BRITISH COUNCIL', 'SEOUL', 'KOREA (REPUBLIC OF)','SEA','British Council 4F, Hungkuk Life Insurance Bldg., 226, Sinmunno 1-Ga, Jongro-Gu, Seoul, 110-786 Korea','Park Eunyoung','Eunyoung.park@britishcouncil.or.kr',NULL),
		('KW001','BRITISH COUNCIL', 'KUWAIT', 'KUWAIT','AMESA1','2, Block 2, Eisa Abdullah Bahman Street, Mansouriya, P O Box 345, 13004 Safat, Kuwait','Nimrod D''Silva','Nimrod.DSilva@kw.britishcouncil.org','tatyana.khazova@kz.britishcouncil.org'),
		('KZ001','BRITISH COUNCIL', 'KAZAKHSTAN', 'KAZAKHSTAN','Europe','British Embassy, British Council, Examinations Department, Samal Towers, block A-2, 11th floor, 97 Zholdasbekov street, Almaty 050051, Kazakhstan','Lyudmila Issayeva','ielts@kz.britishcouncil.org',NULL),
		('LB001','BRITISH COUNCIL', 'BEIRUT', 'LEBANON','AMESA1','Berytech Technology and Health, Mathaf / Sodeco Street, Damascus Road, 2064 1509 Beirut, Lebanon','Khalil Hijal','Khalil.hijal@lb.britishcouncil.org','gerald.yorwerth@britishcouncil.lk'),
		('LK001','BRITISH COUNCIL', 'COLOMBO', 'SRI LANKA','AMESA2','Cultural Attache -Office, 49 Alfred House Gardens, Colombo 03, Sri Lanka','Hiruni Ekanayake','Hiruni.Ekanayake@britishcouncil.org','alison.markwick@britishcouncil.lk'),
		('LK011','BRITISH COUNCIL', 'BRITISH HIGH COMMISSION KANDY', 'SRI LANKA','AMESA2','Cultural Attache - Office, 88/3 Kotugodella Veediya, Kandy, Sri Lanka','Dinuka Galagoda','dinuka.galagoda@britishcouncil.org','Loreta.Pilkiene@britishcouncil.lt'),
		('LT001','BRITISH COUNCIL', 'VILNIUS', 'LITHUANIA','Europe','Antakalnio St. 2, LT - 10308 Vilnius, Lithuania','Laima Augulyte','laima.augulyte@britishcouncil.lt',NULL),
		('LV004','BRITISH COUNCIL', 'BALTIC COUNCIL FOR INTERNATION', 'LATVIA','Europe','office 302, 3rd floor, 33/35 Gertrudes Street, Riga LV1011, Latvia','Inga Benina','inga.benina@balticcouncil.org',NULL),
		('LY002','BRITISH COUNCIL', 'TRIPOLI', 'LIBYAN ARAB JAMAHIRIYA','AMESA1','Hey El Wihda Al -Arabia, Siyahia, PO Box 6797, Tripoli 00218, Libya','Adam Hamroni','Adam.Hamroni@ly.britishcouncil.org',NULL),
		('MA002','BRITISH COUNCIL', 'MOROCCO', 'MOROCCO','AMESA1','11 Allal Ben Abdellah, 5eme Etage, Rabat, Morocco','Imane El Waddi','Imane.Elwaddi@britishcouncil.org.ma',NULL),
		('MK001','BRITISH COUNCIL', 'SKOPJE', 'FYR MACEDONIA','Europe','bul. Coce Delcev 6, PO BOX 562, 1000 Skopje, Republic of Macedonia','Olga Paunceva','olga.paunceva@britishcouncil.org.mk',NULL),
		('MN002','ESP FOUNDATION', 'ESP FOUNDATION', 'MONGOLIA','SEA','ESPF Building, Oyuntnii Str 2, Khoroo 8, Ulaanbaatar, Mongolia','Oyunbeleg Ragchaa','MN002.administrator@esp.mn','chiara@chamber.org.mt'),
		('MT012','THE MALTA CHAMBER OF COMMERCE', 'THE MALTA CHAMBER OF COMMERCE', 'MALTA','Europe','Malta Chambers of Commerce, Exchange Buildings, Republic Street, Valletta VLT 1117, MALTA','Elena Scicluna','education@maltachamber.org.mt',NULL),
		('MU861','BRITISH COUNCIL', 'MAURITIUS', 'MAURITIUS','AMESA1','P.O. Box 111, Royal Road, Rose Hill, Mauritius','Noorani Nojeeb','noorani.nojeeb@mu.britishcouncil.org','cristina.Llamas@britishcouncil.org.mx'),
		('MX030','BRITISH COUNCIL', 'MEXICO', 'MEXICO','UKIA','The British Council AC, Lope de Vega 316, Colonia Chapultepec Morales, (Polanco), Mexico City 11570 Mexico, D.F., MEXICO','Cristina Llamas','cristina.llamas@britishcouncil.org.mx','Naveed.Siddiqui@britishcouncil.org.my'),
		('MY001','BRITISH COUNCIL', 'KUALA LUMPUR', 'MALAYSIA','SEA','Ground Floor West Block, Wisma Selangor Dredging, 142c Jalan Ampang, 50450 Kuala Lumpur, , Malaysia','Intan Shuhana Putri Shuaib','IntanShuhana.Shuaib@britishcouncil.org.my',NULL),
		('MY002','BRITISH COUNCIL', 'PENANG', 'MALAYSIA','SEA','British Council Penang, Wisma Great Eastern, Suite 3A.1 & 3A.2, 25 Lebuh Light, 10200 Penang, Malaysia','Ewen Yeoh','ewen.yeoh@britishcouncil.org.my','Naveed.Siddiqui@britishcouncil.org.my'),
		('MY003','BRITISH COUNCIL', 'SABAH', 'MALAYSIA','SEA','Ground Floor West Block, Wisma Selangor Dredging, 142c Jalan Ampang, 50450 Kuala Lumpur, , Malaysia','Intan Shuhana Putri Shuaib','IntanShuhana.Shuaib@britishcouncil.org.my','Naveed.Siddiqui@britishcouncil.org.my'),
		('MY017','BRITISH COUNCIL', 'SARAWAK', 'MALAYSIA','SEA','Ground Floor West Block, Wisma Selangor Dredging, 142c Jalan Ampang, 50450 Kuala Lumpur, , Malaysia','Intan Shuhana Putri Shuaib','IntanShuhana.Shuaib@britishcouncil.org.my',NULL),
		('NG050','BRITISH COUNCIL', 'ABUJA', 'NIGERIA','AMESA1','Plot 3645, IBB Way, Maitama, Abuja, Nigeria','Iheoma Jibulu','Iheoma.jibulu@ng.britishcouncil.org',NULL),
		('NG150','BRITISH COUNCIL', 'LAGOS', 'NIGERIA','AMESA1','20 Thompson Avenue, Ikoyi, Lagos., Nigeria.','Olayemi Sule','Olayemi.Sule@britishcouncil.org',NULL),
		('NL011','AMSTERDAM BRITISH LANG TRNG', 'AMSTERDAM BRITISH LANG TRNG', 'NETHERLANDS','Europe','BLTC, Oxford House, N.Z. Voorburgwal 328E, 1012 RW, AMSTERDAM, THE NETHERLANDS','Pauline van den Bosch','bltc@bltc.nl','fubergen@online.no'),
		('NO001','FOLKEUNIVERSITETET I BERGEN', 'FOLKEUNIVERSITETET I BERGEN', 'NORWAY','Europe','Friundervisningen Language School, Jonas Reins gate 4, 5838 Bergen, Norway','Chris Jones','chris.jones@folkeuniversitetet.no',NULL),
		('NO002','OSLO', 'OSLO', 'NORWAY','Europe','IELTS Office, Torggata 7, 0181 Oslo, Norway','Rhyder Ramos','ielts.ost@folkeuniversitetet.no',NULL),
		('NP004','BRITISH COUNCIL', 'KATHMANDU', 'NEPAL','AMESA2','British Council Division, British High Commission, 17 Kasturba Gandhi Marg, New Delhi - 110 001, India','Madhulika Verma','Madhulika.Verma@in.britishcouncil.org','ieltsnz029@manukau.ac.nz'),
		('NZ029','AUCKLAND CENTRE M I T/ B C', 'AUCKLAND CENTRE M I T/ B C', 'NEW ZEALAND','SEA','Manukau Inst. of Technology Gate 2, J104, Newbury Street, Otara, Manukau City, New Zealand','Alages Andre','Alages.Andre@manukau.ac.nz',NULL),
		('NZ038','EASTERN INSTITUTE OF TECHNOLOGY', 'EASTERN INSTITUTE OF TECHNOLOGY', 'NEW ZEALAND','SEA','501 Gloucester Street, Taradale, Hawkes Bay, New Zealand','Derek Hall ','dhall@eit.ac.nz',NULL),
		('OM001','BRITISH COUNCIL', 'OMAN', 'OMAN','AMESA1','P O Box 73, Madinat Al Sultan Qaboos, Postal Code 115, Sultanate Of Oman','Nabeel Hussain','nabeel.hussain@om.britishcouncil.org',NULL),
		('OM085','THE LANGUAGE CENTRE, SULTAN QA', 'THE LANGUAGE CENTRE, SULTAN QA', 'OMAN','AMESA1','PO Box 43., Postal Code 123, Al-Khoudh, Oman','Yazen Brahim','yazen@squ.edu.om',NULL),
		('OM200','SOHAR UNIVERSITY', 'SOHAR UNIVERSITY', 'OMAN','AMESA1','P.O. Box: 44, Pc: 311 Sohar, Sultanate Of Oman','Khalid Al Qutaiti','OM200.Administrator@soharuni.edu.om',NULL),
		('PE505','ASOCIACION CULTURAL PERUANO-BR', 'ASOCIACION CULTURAL PERUANO-BR', 'PERU','UKIA','c/o Pilar Ferreyros, IELTS Administrator, Avenida Arequipa 3495, San Isidro, Lima - 27, Peru','Asociacion Cultural Peruano Br','pferreyros@britanico.edu.pe',NULL),
		('PES01','ASOCIACION CULTURAL PERUANO BR', 'ASOCIACION CULTURAL PERUANO BR', 'PERU','UKIA','Asociacion Cultural Peruano Britanica, Av Arequipa 3445, San Isidro, Lima 27, Peru','Pilar Ferreyros','Pilar.ferreyros@britishcouncil.org.co',NULL),
		('PH001','BRITISH COUNCIL', 'MANILA', 'PHILIPPINES','SEA','10th Floor, Taipan Place, F Ortigas Jr. Road, Ortigas Centre, Pasig City 1605, Philippines','Diane Paruli ','Diane.Paruli@britishcouncil.org.ph',NULL),
		('PK010','BRITISH COUNCIL', 'KARACHI', 'PAKISTAN','AMESA2','British Deputy High Commission, Shahrah-e-Iran, Clifton, Karachi 75600, Pakistan','Nazima Jabeen','Nazima.Jabeen@britishcouncil.org.pk','exams.lahore@britishcouncil.org.pk'),
		('PK011','BRITISH COUNCIL', 'LAHORE', 'PAKISTAN','AMESA2','The British Council, 65 Mozang Road, PO Box 88, Lahore 54650, PAKISTAN','Atif Rauf','Atif.Rauf@britishcouncil.org.pk','bcexam@hotmail.com'),
		('PK015','BRITISH COUNCIL', 'ISLAMABAD', 'PAKISTAN','AMESA2','c/o British High Commission, Diplomatic Enclave, Ramna 5, P.O. Box 1135, Islamabad, Pakistan','Munir Hussain','Munir.hussain@britishcouncil.org.pk',NULL),
		('PL001','BRITISH COUNCIL', 'KRAKOW', 'POLAND','Europe','Rynek Glowny 6, 1st Floor, 31-042, Krakow, Poland','Magdalena Malinowska','Magdalena.Malinowska@britishcouncil.pl',NULL),
		('PL002','BRITISH COUNCIL', 'WARSAW', 'POLAND','Europe','Examinations Services- British Council, Aleje Jerozolimskie 59, 00-697 Warsaw, Poland','Ews Paduch','ewa.paduch@britishcouncil.pl',NULL),
		('PS003','BRITISH COUNCIL', 'PALESTINIAN TE', 'PALESTINIAN TERRITORY','AMESA1','The British Council, P O Box 19136, 31 Nablus Road, Jerusalem, 97200','Nadeen Jarrar','nadeen.jarrar@ps.britishcouncil.org','simona.demuro@pt.britishcouncil.org'),
		('PT008','BRITISH COUNCIL', 'LISBON', 'PORTUGAL','Europe','c/o Tim Perry, British Council, Rua Luis Fernandes, No 1-3, 1249 - 062 Lisbon, PORTUGAL','Manuela Coelho','Manuela.Coelho@pt.britishcouncil.org',' Manuela.Coelho@pt.britishcouncil.org'),
		('PT021','BRITISH COUNCIL', 'PORTO', 'PORTUGAL','Europe','c/o Tim Perry, British Council Lisbon, Rua Luis Fernandes, 1-3, Lisbon 1249-062, PORTUGAL','Manuela Coelho','exams.porto@pt.britishcouncil.org',NULL),
		('QA001','BRITISH COUNCIL', 'DOHA', 'QATAR','AMESA1','PO Box 2992, Doha, QATAR','Yusuf Hameed','Yusuf.Hameed@qa.britishcouncil.org',NULL),
		('QA044','FOUNDATION PROGRAM-QATAR UNIVE', 'FOUNDATION PROGRAM-QATAR UNIVE', 'QATAR','AMESA1','Foundation Program-, Qatar University, P.O.Box 2713, Doha, Qatar','Bino Sarah Paul','binosarah@qu.edu.qa',NULL),
		('RO001','BRITISH COUNCIL', 'BUCHAREST', 'ROMANIA','Europe','Calea Dorobantilor 14, 010572 Bucharest, Romania','Lavinia Sturzu','Lavinia.Sturzu@britishcouncil.ro',NULL),
		('SA100','BRITISH COUNCIL', 'JEDDAH', 'SAUDI ARABIA','AMESA2','P.O. Box 3424, 4th Floor Farsi Centre, Waly Al Ahd Street, Jeddah 21471, Saudi Arabia','Tahir Hussain','Tahir.hussain1@sa.britishcouncil.org',NULL),
		('SA102','BRITISH COUNCIL', 'RIYADH', 'SAUDI ARABIA','AMESA2','Office No. C-14, 3rd Floor, Al-Fazary Square, Diplomatic Quarter, PO Box 58012, Riyadh 11594, Saudi Arabia','Baiju Kuppanath','baiju.kuppanath@sa.britishcouncil.org',NULL),
		('SA105','BRITISH COUNCIL', 'DAMMAM', 'SAUDI ARABIA','AMESA2','7 floor Al-Rashid Towers, King Abdulaziz street Al Khobar, PO Box 8387, Dammam 31482, Kingdom of Saudi Arabia, Saudi Arabia','Shibu Sharafuras','Sharafuras.Shibu@sa.britishcouncil.org','; Nada.Issam@sd.britishcouncil.org'),
		('SD001','BRITISH COUNCIL', 'SUDAN', 'SUDAN','AMESA2','14 Abu Sinn Street, Central Khartoum, PO Box 1253, Khartoum, SUDAN','Amro Atabani','Amro.Atabani@sd.britishcouncil.org',NULL),
		('SE004','GOTEBORG FOLKUNIVERSITETET', 'GOTEBORG FOLKUNIVERSITETET', 'SWEDEN','Europe','Norra Allégatan 6, Box 2542, 403 17 Goteborg, SWEDEN','Josephine Scheres Tropp','josephine.scheres@folkuniversitetet.se',NULL),
		('SE008','LUND FOLKUNIVERSITETET', 'LUND FOLKUNIVERSITETET', 'SWEDEN','Europe','Skomakareg 8, 223 50 Lund, Sweden','Petra Hydén','petra.hyden@folkunivbersitetet.se','ielts@folkuniversitetet.se'),
		('SE011','STOCKHOLM FOLKUNIVERSITETET', 'STOCKHOLM FOLKUNIVERSITETET', 'SWEDEN','Europe','Folkuniversitetet, Attn IELTS Administrator, Kungstensgatan 45, 113 59 Stockholm, Sweden','Alexis Orphanides','ielts@folkuniversitetet.se','fam.siewleng@britishcouncil.org.sg'),
		('SG002','BRITISH COUNCIL', 'SINGAPORE LI', 'SINGAPORE','SEA','30 Napier Road, Singapore 258509','Rachel Fung','Rachel.Fung@britishcouncil.org.sg',NULL),
		('SI003','BRITISH COUNCIL', 'LJUBLJANA', 'SLOVENIA','Europe','British Council, Trg republike 3, 1000 Ljubljana, Slovenia','Silvia Jereb','ielts@britishcouncil.si',NULL),
		('SK005','BRITISH COUNCIL', 'BRATISLAVA', 'SLOVAKIA','Europe','The British Council, Panska 17, PO Box 68, 81499, Bratislava, SLOVAKIA','Martina Mrazova','martina.mrazova@britishcouncil.sk',NULL),
		('TH001','BRITISH COUNCIL', 'BANGKOK', 'THAILAND','SEA','254 Chulalongkorn Soi 64, Siam Square, Phayathai Road, Pathumwan, , Bangkok 10330, Thailand','Wanrawee Namsanguan','Wanrawee.Namsanguan@britishcouncil.or.th','Chiangmai@britishcouncil.or.th'),
		('TH002','BRITISH COUNCIL', 'CHIANG MAI', 'THAILAND','SEA','British Council Chiang Mai, 198 Bumrungraj Road, Tumbon Watgate, Amphur Muang, Chiang Mai 50000, Thailand','Patcharagan Doungkham','patcharagan.doungkham@britishcouncil.or.th',NULL),
		('TN001','BRITISH COUNCIL', 'TUNIS', 'TUNISIA','AMESA1','87, Avenue Mohamed V, 1002 Tunis, Tunisia','Rihab Ben Meftah','Rihab.Benmeftah@tn.britishcouncil.org','aysegul.gurek@britishcouncil.org.tr'),
		('TR002','BRITISH COUNCIL', 'EGITIM HIZMETL', 'TURKEY','Europe','Maya Akar Centre, Buyukdere Cad. No: 100-101, 5th floor, Esentepe, Istanbul, , Turkey','Eda Akbulut','eda.akbulut@britishcouncil.org.tr',NULL),
		('TT120','CENTRE FOR LANGUAGE LEARNING', 'CENTRE FOR LANGUAGE LEARNING', 'TRINIDAD AND TOBAGO','UKIA','University of the West Indies, St Augustine, Trinidad & Tobago','Amina Ibrahim-Ali','amina.ibrahim-ali@sta.uwi.edu',NULL),
		('TTS01','UNIVERSITY OF THE WEST INDIES', 'UNIVERSITY OF THE WEST INDIES', 'TRINIDAD AND TOBAGO','UKIA','IELTS Business Office, Lewis Avenue, University of the West Indies, St Augustine, Port of Spain, Trinidad & Tobago','Amina Ibrahim-Ali','Amina.ibrahimali@britishcouncil.org.tt',NULL),
		('TW010','BRITISH COUNCIL', 'TAIWAN', 'TAIWAN','SEA','26F, No. 9-11, Song Gao Road, Taipei 110, Taiwan','Zoe Zhang','Zoe.Zhang@britishcouncil.org.tw',NULL),
		('TZ003','BRITISH COUNCIL', 'DAR ES SALAAM', 'TANZANIA','AMESA2','Samora Avenue, P O Box 9100, Dar Es Salaam, Tanzania','Nora Ishengoma','norah.ishengoma@britishcouncil.or.tz',NULL),
		('UA001','BRITISH COUNCIL', 'KIEV', 'UKRAINE','Europe','4/12 Hryhoriya Skovorody St, Kiev 04070, Ukraine','Yulia Samaichuk','yulia.samaichuk@britishcouncil.org.ua',NULL),
		('UG001','BRITISH COUNCIL', 'KAMPALA', 'UGANDA','AMESA2','Plot 4 Windsor Loop, Off Kira Road, Kamwokya, PO Box 7070, Uganda','Mark Mushabe','mark.mushabe@britishcouncil.or.ug','acorbo@anglo.edu.uy'),
		('UY001','ANGLO MONTEVIDEO', 'ANGLO MONTEVIDEO', 'URUGUAY','UKIA','Instituto Cultural Anglo Uruguayo, San Jose 1426, 11200 - Montevideo, Uruguay','Adda Corbo','acorbo@anglo.edu.uy',NULL),
		('UZ025','BRITISH COUNCIL', 'UZBEKISTAN', 'UZBEKISTAN','Europe','British Council, 107B, Amir Temur Street, , Tashkent, 100084, Uzbekistan','Gulnoz Nadjemidinova','gulnoz.nadjemidinova@britishcouncil.uz',NULL),
		('VE001','BRITISH COUNCIL', 'CARACAS', 'VENEZUELA','UKIA','The British Council, Torre Credicard, Piso 3, Avenida Principal de El Bosque, Apartado 65131, Caracas 1050, VENEZUELA','Jesús Gómez','jesus.gomez@britishcouncil.org.ve','nhung.nguyen@britishcouncil.org.vn'),
		('VN002','BRITISH COUNCIL', 'VIETNAM - HANOI', 'VIETNAM','SEA','20 Thuy Khue Street, Tay Ho District, Hanoi, Vietnam','Ngoc Nguyenphuong','Ngoc.NguyenPhuong@britishcouncil.org.vn',NULL),
		('VN028','BRITISH COUNCIL', 'VIETNAM - HO CHI MINH', 'VIETNAM','SEA','25 Le Duan Street, District 1, Ho Chi Minh City, Vietnam','Huong Vo','Huong.Vo@britishcouncil.org.vn',NULL),
		('ZA001','BRITISH COUNCIL', 'JOHANNESBURG', 'SOUTH AFRICA','AMESA1','275 Jan Smuts Avenue / Dunkeld Corner, Cnr Jan Smuts and Bompass Road, Dunkeld West, Johannesburg 2196, South Africa','Auspicious Ndlovu','Auspicious.Ndlovu@britishcouncil.org',NULL),
		('ZM601','BRITISH COUNCIL', 'LUSAKA', 'ZAMBIA','AMESA1','Aquarius House, Katima Mulilo Road, PO Box 34571, Lusaka','Marion Chileshe Mumba','MarionChileshe.Mumba@britishcouncil.org.zm',NULL),
		('ZW001','BRITISH COUNCIL', 'HARARE', 'ZIMBABWE','AMESA1','British Council, 16 Cork Road, Belgravia, Harare','Elvis Tarasana','Elvis.Tarasana@britishcouncil.org.zw',NULL),

		('AR033','British Council','Argentina','ARGENTINA','UKIA','Marcelo T. De Alvear 590. 4 floor, Ciudad Autonoma de Buenos Aires, Buenos Aires, 1058',NULL,NULL,NULL),
		('DR001','British Council','Santo Domingo','Dominican Republic','UKIA','Dominican Republic, Santo Domingo',NULL,NULL,NULL),
		('SE001','British Council','Stockholm','Sweden','EUROPE','Folkuniversitetet SE011, Kungstensgatan 45, Stockholm, 113 59',NULL,NULL,NULL),

		('12219','London Crest Open Centre - Venue to be confirmed 5  working days before the exam date','London Crest Open Centre','United Kingdom','UKIA','Jubilee House, Stanmore, London, HA7 4RY',NULL,NULL,NULL),
		('12257','Middlesex University','Middlesex University','United Kingdom','UKIA','The Testing Centre, The Burroughs, Hendon, London, UK, NW4 4BT ',NULL,NULL,NULL),
		('20426','City College Coventry','City College Coventry','United Kingdom','UKIA','50 Swanswell Street, Coventry, CV1 5DG',NULL,NULL,NULL),
		('70283','University of Glasgow','University of Glasgow','United Kingdom','UKIA','IELTS Test Centre, University of Glasgow, Language Centre, Bute Gardens, Glasgow, G12 8RS',NULL,NULL,NULL),
		('AE055','CES (Centre for Exam Services)','CES- Kharazmi Islamic Republic of Iran','Iran','AMESA1','309 West Mirdamad Blvd Toward Vali Asr Avenue, Tehran, Islamic Republic of Iran, Tehran',NULL,NULL,NULL),
		('CA074','GEOS Language','GEOS Languages Plus','Canada','UKIA','Suite 140, 1040 7th Ave SW, Calgary, Alberta, T2P3G9',NULL,NULL,NULL),
		('CZ006','British Council','Britske Centrum KUP','Czech Republic','Europe','Krizkovskeho 8, OLOMOUC, Prague, 771 11',NULL,NULL,NULL),
		('CZ007','British Council','British Council Brno','Czech Republic','Europe','Solnicni 12, 3rd floor, Brno, Czech Republic, 602 00',NULL,NULL,NULL),
		('ER001','British Council','British Council Eritrea','Eritrea','AMESA2','175-11,Street No 23, Maekel Ketema, Asmara, Eritrea',NULL,NULL,NULL),
		('NG166','British Council','British Council Port Harcourt','Nigeria','AMESA1','127 Olu Obasanjo Road, GRA Phase 2, Port Harcourt',NULL,NULL,NULL),
		('PY001','Anglo English','Asociación Cultural Paraguayo Británica','Paraguay','UKIA','Juan de Salazar 391, Ascuncion',NULL,NULL,NULL)

	) AS Source ([CentreNumber],[Organisation],[Name],[SubRegion],[Region],[Address],[Administrator],[PrimaryEmail],[SecondaryEmail])

	ON (Target.[CentreNumber] = Source.[CentreNumber])

	WHEN MATCHED THEN 
		UPDATE SET 
			[Name] = Source.[Name],
			[SubRegion] = Source.[SubRegion],
			[Region] = Source.[Region],
			[Address] = Source.[Address],
			[Administrator] = Source.[Administrator],
			[PrimaryEmail] = Source.[PrimaryEmail],
			[SecondaryEmail] = Source.[SecondaryEmail]
			
			
	-- insert new rows 
	WHEN NOT MATCHED BY TARGET THEN 
		INSERT ([CentreNumber],[Organisation],[Name],[SubRegion],[Region],[Address],[Administrator],[PrimaryEmail],[SecondaryEmail])
		VALUES ([CentreNumber],[Organisation],[Name],[SubRegion],[Region],[Address],[Administrator],[PrimaryEmail],[SecondaryEmail])

	-- delete rows that are in the target but not the source 
	WHEN NOT MATCHED BY SOURCE THEN 
		DELETE;